export const unis = [
    { value: 'fh aachen', label: 'FH Aachen', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'rwth aachen (rwth)', label: 'RWTH Aachen (RWTH)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'hochschule aalen (haa)', label: 'Hochschule Aalen (HAA)', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule albstadt-sigmaringen (has)', label: 'Hochschule Albstadt-Sigmaringen (HAS)', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'alanus hochschule für kunst und gesellschaft (ahkg) (alfter)', label: 'Alanus Hochschule für Kunst und Gesellschaft (AHKG) (Alfter)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'allensbach hochschule (abhs)', label: 'Allensbach Hochschule (ABHS)', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'fachhochschule für verwaltung und dienstleistung (fvd) (altenholz, reinfeld)', label: 'Fachhochschule für Verwaltung und Dienstleistung (FVD) (Altenholz, Reinfeld)', state: 'Schleswig-Holstein', status: 'staatlich' },
  { value: 'ostbayerische technische hochschule amberg-weiden (oth amberg-weiden)', label: 'Ostbayerische Technische Hochschule Amberg-Weiden (OTH Amberg-Weiden)', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule ansbach (hah)', label: 'Hochschule Ansbach (HAH)', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule aschaffenburg (hab)', label: 'Hochschule Aschaffenburg (HAB)', state: 'Bayern', status: 'staatlich' },
  { value: 'fachhochschule polizei sachsen-anhalt (fps) (aschersleben)', label: 'Fachhochschule Polizei Sachsen-Anhalt (FPS) (Aschersleben)', state: 'Sachsen-Anhalt', status: 'staatlich' },
  { value: 'hochschule augsburg (hsa)', label: 'Hochschule Augsburg (HSA)', state: 'Bayern', status: 'staatlich' },
  { value: 'universität augsburg (uab)', label: 'Universität Augsburg (UAB)', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule der bayerischen wirtschaft (hdbw)', label: 'Hochschule der Bayerischen Wirtschaft (HDBW)', state: 'Bayern', status: 'privat' },
  { value: 'hochschule der deutschen gesetzlichen unfallversicherung (hgu) (bad hersfeld)', label: 'Hochschule der Deutschen Gesetzlichen Unfallversicherung (HGU) (Bad Hersfeld)', state: 'Hessen', status: 'privat' },
  { value: 'accadis hochschule bad homburg (ahbh)', label: 'accadis Hochschule Bad Homburg (AHBH)', state: 'Hessen', status: 'privat' },
  { value: 'internationale hochschule bad honnef bonn (ihbh)', label: 'Internationale Hochschule Bad Honnef Bonn (IHBH)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'fachhochschule für rechtspflege nordrhein-westfalen (ffr) (bad münstereifel)', label: 'Fachhochschule für Rechtspflege Nordrhein-Westfalen (FFR) (Bad Münstereifel)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'diploma hochschule (dphs) (bad sooden-allendorf)', label: 'Diploma Hochschule (DPHS) (Bad Sooden-Allendorf)', state: 'Hessen', status: 'privat' },
  { value: 'otto-friedrich-universität bamberg', label: 'Otto-Friedrich-Universität Bamberg', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule für evangelische kirchenmusik bayreuth (hekm)', label: 'Hochschule für evangelische Kirchenmusik Bayreuth (HEKM)', state: 'Bayern', status: 'konfessionell' },
  { value: 'universität bayreuth (ubt)', label: 'Universität Bayreuth (UBT)', state: 'Bayern', status: 'staatlich' },
  { value: 'akkon-hochschule für humanwissenschaften (ahfh) (berlin)', label: 'Akkon-Hochschule für Humanwissenschaften (AHFH) (Berlin)', state: 'Berlin', status: 'privat' },
  { value: 'alice salomon hochschule berlin (ash)', label: 'Alice Salomon Hochschule Berlin (ASH)', state: 'Berlin', status: 'staatlich' },
  { value: 'bard college berlin, a liberal arts university (bcb)', label: 'Bard College Berlin, A Liberal Arts University (BCB)', state: 'Berlin', status: 'privat' },
  { value: 'berlin international university of applied sciences (baub)', label: 'Berlin International University of Applied Sciences (BAUB)', state: 'Berlin', status: 'privat' },
  { value: 'bbw hochschule (bbwh) (berlin)', label: 'bbw Hochschule (BBWH) (Berlin)', state: 'Berlin', status: 'privat' },
  { value: 'btk – hochschule für gestaltung (btkb)', label: 'BTK – Hochschule für Gestaltung (BTKB)', state: 'Berlin', status: 'privat' },
  { value: 'bsp business school berlin (bbsb)', label: 'BSP Business School Berlin (BBSB)', state: 'Berlin', status: 'privat' },
  { value: 'beuth hochschule für technik berlin', label: 'Beuth Hochschule für Technik Berlin', state: 'Berlin', status: 'staatlich' },
  { value: 'dekra hochschule berlin (dhsb)', label: 'Dekra Hochschule Berlin (DHSB)', state: 'Berlin', status: 'privat' },
  { value: 'design akademie berlin, hochschule für kommunikation und design (fhda) (berlin)', label: 'design akademie berlin, Hochschule für Kommunikation und Design (FHDA) (Berlin)', state: 'Berlin', status: 'privat' },
  { value: 'deutsche film- und fernsehakademie berlin (dff)', label: 'Deutsche Film- und Fernsehakademie Berlin (DFF)', state: 'Berlin', status: 'staatlich[4]' },
  { value: 'deutsche universität für weiterbildung (dufw)', label: 'Deutsche Universität für Weiterbildung (DUFW)', state: 'Berlin', status: 'privat' },
  { value: 'escp europe wirtschaftshochschule berlin', label: 'ESCP Europe Wirtschaftshochschule Berlin', state: 'Berlin', status: 'privat' },
  { value: 'esmod internationale kunsthochschule für mode (ikhm) (berlin)', label: 'ESMOD Internationale Kunsthochschule für Mode (IKHM) (Berlin)', state: 'Berlin', status: 'privat' },
  { value: 'esmt european school of management and technology (esmt) (berlin)', label: 'ESMT European School of Management and Technology (ESMT) (Berlin)', state: 'Berlin', status: 'privat' },
  { value: 'evangelische hochschule berlin (ehsb)', label: 'Evangelische Hochschule Berlin (EHSB)', state: 'Berlin', status: 'konfessionell' },
  { value: 'hochschule der populären künste (fhpk)', label: 'Hochschule der populären Künste (FHPK)', state: 'Berlin', status: 'privat' },
  { value: 'hochschule für medien, kommunikation und wirtschaft (hmkw) (berlin)', label: 'Hochschule für Medien, Kommunikation und Wirtschaft (HMKW) (Berlin)', state: 'Berlin', status: 'privat' },
  { value: 'hochschule für technik und wirtschaft berlin (htw)', label: 'Hochschule für Technik und Wirtschaft Berlin (HTW)', state: 'Berlin', status: 'staatlich' },
  { value: 'hochschule für wirtschaft, technik und kultur berlin (hwtk)', label: 'Hochschule für Wirtschaft, Technik und Kultur Berlin (HWTK)', state: 'Berlin', status: 'privat' },
  { value: 'hochschule für wirtschaft und recht berlin (hwr)', label: 'Hochschule für Wirtschaft und Recht Berlin (HWR)', state: 'Berlin', status: 'staatlich' },
  { value: 'freie universität berlin (fub)', label: 'Freie Universität Berlin (FUB)', state: 'Berlin', status: 'staatlich' },
  { value: 'german open business school (gobs) (berlin)', label: 'German open Business School (GOBS) (Berlin)', state: 'Berlin', status: 'privat' },
  { value: 'hertie school of governance (hsog) (berlin)', label: 'Hertie School of Governance (HSOG) (Berlin)', state: 'Berlin', status: 'privat' },
  { value: 'h:g hochschule für gesundheit und sport (hsgs) (berlin)', label: 'H:G Hochschule für Gesundheit und Sport (HSGS) (Berlin)', state: 'Berlin', status: 'privat' },
  { value: 'hochschule für musik „hanns eisler“ berlin (hmb)', label: 'Hochschule für Musik „Hanns Eisler“ Berlin (HMB)', state: 'Berlin', status: 'staatlich' },
  { value: 'hochschule für schauspielkunst „ernst busch“ berlin (hsb)', label: 'Hochschule für Schauspielkunst „Ernst Busch“ Berlin (HSB)', state: 'Berlin', status: 'staatlich' },
  { value: 'humboldt-universität zu berlin (hub)', label: 'Humboldt-Universität zu Berlin (HUB)', state: 'Berlin', status: 'staatlich' },
  { value: 'ib-hochschule berlin (ibhb)', label: 'IB-Hochschule Berlin (IBHB)', state: 'Berlin', status: 'privat' },
  { value: 'international psychoanalytic university berlin (ipub)', label: 'International Psychoanalytic University Berlin (IPUB)', state: 'Berlin', status: 'privat' },
  { value: 'katholische hochschule für sozialwesen berlin (khsw)', label: 'Katholische Hochschule für Sozialwesen Berlin (KHSW)', state: 'Berlin', status: 'konfessionell' },
  { value: 'kunsthochschule berlin-weißensee (khb)', label: 'Kunsthochschule Berlin-Weißensee (KHB)', state: 'Berlin', status: 'staatlich' },
  { value: 'mediadesign hochschule (mdhb) (berlin)', label: 'Mediadesign Hochschule (MDHB) (Berlin)', state: 'Berlin', status: 'privat' },
  { value: 'psychologische hochschule berlin (phsb)', label: 'Psychologische Hochschule Berlin (PHSB)', state: 'Berlin', status: 'privat' },
  { value: 'srh hochschule berlin (srhb)', label: 'SRH Hochschule Berlin (SRHB)', state: 'Berlin', status: 'privat' },
  { value: 'steinbeis-hochschule berlin (sbhb)', label: 'Steinbeis-Hochschule Berlin (SBHB)', state: 'Berlin', status: 'privat' },
  { value: 'technische universität berlin (tub)', label: 'Technische Universität Berlin (TUB)', state: 'Berlin', status: 'staatlich' },
  { value: 'touro college berlin', label: 'Touro College Berlin', state: 'Berlin', status: 'privat' },
  { value: 'universität der künste berlin', label: 'Universität der Künste Berlin', state: 'Berlin', status: 'staatlich' },
  { value: 'quadriga hochschule berlin', label: 'Quadriga Hochschule Berlin', state: 'Berlin', status: 'privat' },
  { value: 'hochschule anhalt (bernburg, dessau und köthen)', label: 'Hochschule Anhalt (Bernburg, Dessau und Köthen)', state: 'Sachsen-Anhalt', status: 'staatlich' },
  { value: 'hochschule biberach', label: 'Hochschule Biberach', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'fachhochschule bielefeld', label: 'Fachhochschule Bielefeld', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'fachhochschule der diakonie (bielefeld)', label: 'Fachhochschule der Diakonie (Bielefeld)', state: 'Nordrhein-Westfalen', status: 'konfessionell' },
  { value: 'fachhochschule des mittelstands (bielefeld)', label: 'Fachhochschule des Mittelstands (Bielefeld)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'universität bielefeld', label: 'Universität Bielefeld', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'technische hochschule bingen', label: 'Technische Hochschule Bingen', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'ebz business school (bochum)', label: 'EBZ Business School (Bochum)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'evangelische fachhochschule rheinland-westfalen-lippe (bochum)', label: 'Evangelische Fachhochschule Rheinland-Westfalen-Lippe (Bochum)', state: 'Nordrhein-Westfalen', status: 'konfessionell' },
  { value: 'hochschule bochum', label: 'Hochschule Bochum', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'hochschule für gesundheit (bochum)', label: 'Hochschule für Gesundheit (Bochum)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'ruhr-universität bochum', label: 'Ruhr-Universität Bochum', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'technische hochschule georg agricola (bochum)', label: 'Technische Hochschule Georg Agricola (Bochum)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'hochschule der sparkassen-finanzgruppe (bonn)', label: 'Hochschule der Sparkassen-Finanzgruppe (Bonn)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'rheinische friedrich-wilhelms-universität bonn', label: 'Rheinische Friedrich-Wilhelms-Universität Bonn', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'hochschule bonn-rhein-sieg', label: 'Hochschule Bonn-Rhein-Sieg', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'technische hochschule brandenburg', label: 'Technische Hochschule Brandenburg', state: 'Brandenburg', status: 'staatlich' },
  { value: 'medizinische hochschule brandenburg theodor fontane', label: 'Medizinische Hochschule Brandenburg Theodor Fontane', state: 'Brandenburg', status: 'privat' },
  { value: 'hochschule für bildende künste braunschweig', label: 'Hochschule für Bildende Künste Braunschweig', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'technische universität braunschweig', label: 'Technische Universität Braunschweig', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'hochschule bremen', label: 'Hochschule Bremen', state: 'Bremen', status: 'staatlich' },
  { value: 'apollon hochschule der gesundheitswirtschaft (bremen)', label: 'Apollon Hochschule der Gesundheitswirtschaft (Bremen)', state: 'Bremen', status: 'privat' },
  { value: 'hochschule für internationale wirtschaft und logistik (bremen)', label: 'Hochschule für internationale Wirtschaft und Logistik (Bremen)', state: 'Bremen', status: 'privat' },
  { value: 'hochschule für künste bremen', label: 'Hochschule für Künste Bremen', state: 'Bremen', status: 'staatlich' },
  { value: 'hochschule für öffentliche verwaltung bremen', label: 'Hochschule für Öffentliche Verwaltung Bremen', state: 'Bremen', status: 'staatlich' },
  { value: 'jacobs university bremen', label: 'Jacobs University Bremen', state: 'Bremen', status: 'privat' },
  { value: 'universität bremen', label: 'Universität Bremen', state: 'Bremen', status: 'staatlich' },
  { value: 'hochschule bremerhaven', label: 'Hochschule Bremerhaven', state: 'Bremen', status: 'staatlich' },
  { value: 'europäische fachhochschule (brühl)', label: 'Europäische Fachhochschule (Brühl)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'fachhochschule des bundes für öffentliche verwaltung (brühl)', label: 'Fachhochschule des Bundes für öffentliche Verwaltung (Brühl)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'hochschule 21 (buxtehude)', label: 'Hochschule 21 (Buxtehude)', state: 'Niedersachsen', status: 'privat' },
  { value: 'srh hochschule für wirtschaft und medien calw', label: 'SRH Hochschule für Wirtschaft und Medien Calw', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'technische universität chemnitz', label: 'Technische Universität Chemnitz', state: 'Sachsen', status: 'staatlich' },
  { value: 'technische universität clausthal', label: 'Technische Universität Clausthal', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'hochschule für angewandte wissenschaften coburg', label: 'Hochschule für angewandte Wissenschaften Coburg', state: 'Bayern', status: 'staatlich' },
  { value: 'brandenburgische technische universität cottbus-senftenberg', label: 'Brandenburgische Technische Universität Cottbus-Senftenberg', state: 'Brandenburg', status: 'staatlich' },
  { value: 'evangelische hochschule darmstadt', label: 'Evangelische Hochschule Darmstadt', state: 'Hessen', status: 'konfessionell' },
  { value: 'hochschule darmstadt', label: 'Hochschule Darmstadt', state: 'Hessen', status: 'staatlich' },
  { value: 'technische universität darmstadt', label: 'Technische Universität Darmstadt', state: 'Hessen', status: 'staatlich' },
  { value: 'technische hochschule deggendorf', label: 'Technische Hochschule Deggendorf', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule für musik detmold', label: 'Hochschule für Musik Detmold', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'fachhochschule dortmund', label: 'Fachhochschule Dortmund', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'international school of management (dortmund)', label: 'International School of Management (Dortmund)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'technische universität dortmund', label: 'Technische Universität Dortmund', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'dresden international university', label: 'Dresden International University', state: 'Sachsen', status: 'privat' },
  { value: 'evangelische hochschule für kirchenmusik dresden', label: 'Evangelische Hochschule für Kirchenmusik Dresden', state: 'Sachsen', status: 'konfessionell' },
  { value: 'evangelische hochschule für soziale arbeit dresden', label: 'Evangelische Hochschule für Soziale Arbeit Dresden', state: 'Sachsen', status: 'konfessionell' },
  { value: 'fachhochschule dresden', label: 'Fachhochschule Dresden', state: 'Sachsen', status: 'privat' },
  { value: 'hochschule für bildende künste dresden', label: 'Hochschule für Bildende Künste Dresden', state: 'Sachsen', status: 'staatlich' },
  { value: 'hochschule für musik carl maria von weber dresden', label: 'Hochschule für Musik Carl Maria von Weber Dresden', state: 'Sachsen', status: 'staatlich' },
  { value: 'hochschule für technik und wirtschaft dresden', label: 'Hochschule für Technik und Wirtschaft Dresden', state: 'Sachsen', status: 'staatlich' },
  { value: 'palucca hochschule für tanz dresden', label: 'Palucca Hochschule für Tanz Dresden', state: 'Sachsen', status: 'staatlich' },
  { value: 'technische universität dresden', label: 'Technische Universität Dresden', state: 'Sachsen', status: 'staatlich' },
  { value: 'universität duisburg-essen', label: 'Universität Duisburg-Essen', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'hochschule düsseldorf', label: 'Hochschule Düsseldorf', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'fliedner fachhochschule düsseldorf', label: 'Fliedner Fachhochschule Düsseldorf', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'heinrich-heine-universität düsseldorf', label: 'Heinrich-Heine-Universität Düsseldorf', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'ist-hochschule für management (düsseldorf)', label: 'IST-Hochschule für Management (Düsseldorf)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'kunstakademie düsseldorf', label: 'Kunstakademie Düsseldorf', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'robert schumann hochschule düsseldorf', label: 'Robert Schumann Hochschule Düsseldorf', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'hochschule für nachhaltige entwicklung eberswalde', label: 'Hochschule für nachhaltige Entwicklung Eberswalde', state: 'Brandenburg', status: 'staatlich' },
  { value: 'fachhochschule für finanzen (edenkoben)', label: 'Fachhochschule für Finanzen (Edenkoben)', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'katholische universität eichstätt-ingolstadt', label: 'Katholische Universität Eichstätt-Ingolstadt', state: 'Bayern', status: 'konfessionell' },
  { value: 'nordakademie (elmshorn)', label: 'Nordakademie (Elmshorn)', state: 'Schleswig-Holstein', status: 'privat' },
  { value: 'theologische hochschule elstal', label: 'Theologische Hochschule Elstal', state: 'Brandenburg', status: 'konfessionell' },
  { value: 'hochschule emden/leer', label: 'Hochschule Emden/Leer', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'hochschule für angewandtes management (ismaning)', label: 'Hochschule für angewandtes Management (Ismaning)', state: 'Bayern', status: 'privat' },
  { value: 'adam-ries-fachhochschule (erfurt)', label: 'Adam-Ries-Fachhochschule (Erfurt)', state: 'Thürigen', status: 'privat' },
  { value: 'fachhochschule erfurt', label: 'Fachhochschule Erfurt', state: 'Thürigen', status: 'staatlich' },
  { value: 'universität erfurt', label: 'Universität Erfurt', state: 'Thürigen', status: 'staatlich' },
  { value: 'friedrich-alexander-universität erlangen-nürnberg', label: 'Friedrich-Alexander-Universität Erlangen-Nürnberg', state: 'Bayern', status: 'staatlich' },
  { value: 'folkwang universität der künste (essen)', label: 'Folkwang Universität der Künste (Essen)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'hochschule der bildenden künste essen', label: 'Hochschule der bildenden Künste Essen', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'fom hochschule (essen)', label: 'FOM Hochschule (Essen)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'hochschule esslingen', label: 'Hochschule Esslingen', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'theologische hochschule ewersbach', label: 'Theologische Hochschule Ewersbach', state: 'Hessen', status: 'konfessionell' },
  { value: 'hochschule flensburg (fachhochschule)', label: 'Hochschule Flensburg (Fachhochschule)', state: 'Schleswig-Holstein', status: 'staatlich' },
  { value: 'europa-universität flensburg', label: 'Europa-Universität Flensburg', state: 'Schleswig-Holstein', status: 'staatlich' },
  { value: 'frankfurt university of applied sciences', label: 'Frankfurt University of Applied Sciences', state: 'Hessen', status: 'staatlich' },
  { value: 'frankfurt school of finance & management (frankfurt am main)', label: 'Frankfurt School of Finance & Management (Frankfurt am Main)', state: 'Hessen', status: 'privat' },
  { value: 'hochschule für musik und darstellende kunst frankfurt am main', label: 'Hochschule für Musik und Darstellende Kunst Frankfurt am Main', state: 'Hessen', status: 'staatlich' },
  { value: 'johann wolfgang goethe-universität frankfurt am main', label: 'Johann Wolfgang Goethe-Universität Frankfurt am Main', state: 'Hessen', status: 'staatlich' },
  { value: 'philosophisch-theologische hochschule sankt georgen (frankfurt am main)', label: 'Philosophisch-Theologische Hochschule Sankt Georgen (Frankfurt am Main)', state: 'Hessen', status: 'konfessionell' },
  { value: 'provadis school of international management and technology (frankfurt am main)', label: 'Provadis School of International Management and Technology (Frankfurt am Main)', state: 'Hessen', status: 'privat' },
  { value: 'staatliche hochschule für bildende künste – städelschule (frankfurt am main)', label: 'Staatliche Hochschule für Bildende Künste – Städelschule (Frankfurt am Main)', state: 'Hessen', status: 'staatlich' },
  { value: 'europa-universität viadrina (frankfurt (oder))', label: 'Europa-Universität Viadrina (Frankfurt (Oder))', state: 'Brandenburg', status: 'staatlich' },
  { value: 'technische universität bergakademie freiberg', label: 'Technische Universität Bergakademie Freiberg', state: 'Sachsen', status: 'staatlich' },
  { value: 'albert-ludwigs-universität freiburg', label: 'Albert-Ludwigs-Universität Freiburg', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'evangelische hochschule freiburg', label: 'Evangelische Hochschule Freiburg', state: 'Baden-Württemberg', status: 'konfessionell' },
  { value: 'hochschule für musik freiburg', label: 'Hochschule für Musik Freiburg', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule für kunst, design und populäre musik freiburg', label: 'Hochschule für Kunst, Design und Populäre Musik Freiburg', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'katholische hochschule freiburg', label: 'Katholische Hochschule Freiburg', state: 'Baden-Württemberg', status: 'konfessionell' },
  { value: 'pädagogische hochschule freiburg', label: 'Pädagogische Hochschule Freiburg', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'theologische hochschule friedensau', label: 'Theologische Hochschule Friedensau', state: 'Sachsen-Anhalt', status: 'konfessionell' },
  { value: 'zeppelin universität (friedrichshafen)', label: 'Zeppelin Universität (Friedrichshafen)', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'hochschule fulda', label: 'Hochschule Fulda', state: 'Hessen', status: 'staatlich' },
  { value: 'theologische fakultät fulda', label: 'Theologische Fakultät Fulda', state: 'Hessen', status: 'konfessionell' },
  { value: 'wilhelm löhe hochschule für angewandte wissenschaften (fürth)', label: 'Wilhelm Löhe Hochschule für angewandte Wissenschaften (Fürth)', state: 'Bayern', status: 'privat' },
  { value: 'hochschule furtwangen', label: 'Hochschule Furtwangen', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule geisenheim', label: 'Hochschule Geisenheim', state: 'Hessen', status: 'staatlich' },
  { value: 'fachhochschule für öffentliche verwaltung nordrhein-westfalen (gelsenkirchen)', label: 'Fachhochschule für öffentliche Verwaltung Nordrhein-Westfalen (Gelsenkirchen)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'westfälische hochschule gelsenkirchen bocholt recklinghausen', label: 'Westfälische Hochschule Gelsenkirchen Bocholt Recklinghausen', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'duale hochschule gera-eisenach (dhge)', label: 'Duale Hochschule Gera-Eisenach (DHGE)', state: 'Thürigen', status: 'staatlich' },
  { value: 'srh hochschule für gesundheit gera', label: 'SRH Hochschule für Gesundheit Gera', state: 'Thürigen', status: 'privat' },
  { value: 'freie theologische hochschule gießen', label: 'Freie Theologische Hochschule Gießen', state: 'Hessen', status: 'konfessionell' },
  { value: 'justus-liebig-universität gießen', label: 'Justus-Liebig-Universität Gießen', state: 'Hessen', status: 'staatlich' },
  { value: 'technische hochschule mittelhessen (gießen, friedberg, wetzlar)', label: 'Technische Hochschule Mittelhessen (Gießen, Friedberg, Wetzlar)', state: 'Hessen', status: 'staatlich' },
  { value: 'thüringer fachhochschule für öffentliche verwaltung (gotha, meiningen)', label: 'Thüringer Fachhochschule für öffentliche Verwaltung (Gotha, Meiningen)', state: 'Thürigen', status: 'staatlich' },
  { value: 'georg-august-universität göttingen', label: 'Georg-August-Universität Göttingen', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'private fachhochschule göttingen', label: 'Private Fachhochschule Göttingen', state: 'Niedersachsen', status: 'privat' },
  { value: 'universität greifswald', label: 'Universität Greifswald', state: 'Mecklenburg-Vorpommern', status: 'staatlich' },
  { value: 'fachhochschule für öffentliche verwaltung, polizei und rechtspflege (güstrow)', label: 'Fachhochschule für öffentliche Verwaltung, Polizei und Rechtspflege (Güstrow)', state: 'Mecklenburg-Vorpommern', status: 'staatlich' },
  { value: 'hochschule der deutschen bundesbank (hachenburg)', label: 'Hochschule der Deutschen Bundesbank (Hachenburg)', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'fernuniversität in hagen', label: 'Fernuniversität in Hagen', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'burg giebichenstein kunsthochschule halle', label: 'Burg Giebichenstein Kunsthochschule Halle', state: 'Sachsen-Anhalt', status: 'staatlich' },
  { value: 'evangelische hochschule für kirchenmusik halle', label: 'Evangelische Hochschule für Kirchenmusik Halle', state: 'Sachsen-Anhalt', status: 'konfessionell' },
  { value: 'martin-luther-universität halle-wittenberg', label: 'Martin-Luther-Universität Halle-Wittenberg', state: 'Sachsen-Anhalt', status: 'staatlich' },
  { value: 'bucerius law school (hamburg)', label: 'Bucerius Law School (Hamburg)', state: 'Hamburg', status: 'privat' },
  { value: 'brand academy – hochschule für design und kommunikation (hamburg)', label: 'Brand Academy – Hochschule für Design und Kommunikation (Hamburg)', state: 'Hamburg', status: 'privat' },
  { value: 'ebc hochschule', label: 'EBC Hochschule', state: 'Hamburg', status: 'privat' },
  { value: 'europäische fernhochschule hamburg', label: 'Europäische Fernhochschule Hamburg', state: 'Hamburg', status: 'privat' },
  { value: 'evangelische hochschule für soziale arbeit & diakonie (hamburg)', label: 'Evangelische Hochschule für Soziale Arbeit & Diakonie (Hamburg)', state: 'Hamburg', status: 'konfessionell' },
  { value: 'hafencity universität hamburg', label: 'HafenCity Universität Hamburg', state: 'Hamburg', status: 'staatlich' },
  { value: 'hfh hamburger fern-hochschule', label: 'HFH Hamburger Fern-Hochschule', state: 'Hamburg', status: 'privat' },
  { value: 'hamburg school of business administration', label: 'Hamburg School of Business Administration', state: 'Hamburg', status: 'privat' },
  { value: 'helmut-schmidt-universität (hamburg)', label: 'Helmut-Schmidt-Universität (Hamburg)', state: 'Hamburg', status: 'staatlich' },
  { value: 'hochschule für angewandte wissenschaften hamburg', label: 'Hochschule für Angewandte Wissenschaften Hamburg', state: 'Hamburg', status: 'staatlich' },
  { value: 'hochschule für bildende künste hamburg', label: 'Hochschule für bildende Künste Hamburg', state: 'Hamburg', status: 'staatlich' },
  { value: 'hochschule für musik und theater hamburg', label: 'Hochschule für Musik und Theater Hamburg', state: 'Hamburg', status: 'staatlich' },
  { value: 'norddeutsche akademie für finanzen und steuerrecht (hamburg)', label: 'Norddeutsche Akademie für Finanzen und Steuerrecht (Hamburg)', state: 'Hamburg', status: 'staatlich' },
  { value: 'international business school of service management (hamburg)', label: 'International Business School of Service Management (Hamburg)', state: 'Hamburg', status: 'privat' },
  { value: 'kühne logistics university (hamburg)', label: 'Kühne Logistics University (Hamburg)', state: 'Hamburg', status: 'privat' },
  { value: 'msh medical school hamburg', label: 'MSH Medical School Hamburg', state: 'Hamburg', status: 'privat' },
  { value: 'technische universität hamburg', label: 'Technische Universität Hamburg', state: 'Hamburg', status: 'staatlich' },
  { value: 'universität hamburg', label: 'Universität Hamburg', state: 'Hamburg', status: 'staatlich' },
  { value: 'hochschule weserbergland (hameln)', label: 'Hochschule Weserbergland (Hameln)', state: 'Niedersachsen', status: 'privat' },
  { value: 'hochschule hamm-lippstadt', label: 'Hochschule Hamm-Lippstadt', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'srh hochschule für logistik und wirtschaft hamm', label: 'SRH Hochschule für Logistik und Wirtschaft Hamm', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'fachhochschule für die wirtschaft (hannover)', label: 'Fachhochschule für die Wirtschaft (Hannover)', state: 'Niedersachsen', status: 'privat' },
  { value: 'gottfried wilhelm leibniz universität hannover', label: 'Gottfried Wilhelm Leibniz Universität Hannover', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'hochschule für musik, theater und medien hannover', label: 'Hochschule für Musik, Theater und Medien Hannover', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'hochschule hannover', label: 'Hochschule Hannover', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'kommunale hochschule für verwaltung in niedersachsen (hannover)', label: 'Kommunale Hochschule für Verwaltung in Niedersachsen (Hannover)', state: 'Niedersachsen', status: 'privat' },
  { value: 'leibniz-akademie hannover (hannover)', label: 'Leibniz-Akademie Hannover (Hannover)', state: 'Niedersachsen', status: 'privat' },
  { value: 'medizinische hochschule hannover', label: 'Medizinische Hochschule Hannover', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'tierärztliche hochschule hannover', label: 'Tierärztliche Hochschule Hannover', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'fachhochschule westküste (heide)', label: 'Fachhochschule Westküste (Heide)', state: 'Schleswig-Holstein', status: 'staatlich' },
  { value: 'hochschule für jüdische studien (heidelberg)', label: 'Hochschule für Jüdische Studien (Heidelberg)', state: 'Baden-Württemberg', status: 'konfessionell' },
  { value: 'hochschule für kirchenmusik heidelberg', label: 'Hochschule für Kirchenmusik Heidelberg', state: 'Baden-Württemberg', status: 'konfessionell' },
  { value: 'pädagogische hochschule heidelberg', label: 'Pädagogische Hochschule Heidelberg', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'ruprecht-karls-universität heidelberg', label: 'Ruprecht-Karls-Universität Heidelberg', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'srh hochschule heidelberg', label: 'SRH Hochschule Heidelberg', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'hochschule heilbronn', label: 'Hochschule Heilbronn', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'german graduate school of management and law (heilbronn)', label: 'German Graduate School of Management and Law (Heilbronn)', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'hochschule für kirchenmusik der evangelischen kirche von westfalen (herford)', label: 'Hochschule für Kirchenmusik der Evangelischen Kirche von Westfalen (Herford)', state: 'Nordrhein-Westfalen', status: 'konfessionell' },
  { value: 'fachhochschule für interkulturelle theologie (hermannsburg)', label: 'Fachhochschule für Interkulturelle Theologie (Hermannsburg)', state: 'Niedersachsen', status: 'konfessionell' },
  { value: 'norddeutsche hochschule für rechtspflege (hildesheim)', label: 'Norddeutsche Hochschule für Rechtspflege (Hildesheim)', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'universität hildesheim', label: 'Universität Hildesheim', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'hawk hochschule hildesheim/holzminden/göttingen', label: 'HAWK Hochschule Hildesheim/Holzminden/Göttingen', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'hochschule hof', label: 'Hochschule Hof', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule fresenius (idstein)', label: 'Hochschule Fresenius (Idstein)', state: 'Hessen', status: 'privat' },
  { value: 'technische universität ilmenau', label: 'Technische Universität Ilmenau', state: 'Thürigen', status: 'staatlich' },
  { value: 'technische hochschule ingolstadt', label: 'Technische Hochschule Ingolstadt', state: 'Bayern', status: 'staatlich' },
  { value: 'business and information technology school (iserlohn, hamburg, berlin)', label: 'Business and Information Technology School (Iserlohn, Hamburg, Berlin)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'fachhochschule südwestfalen (iserlohn)', label: 'Fachhochschule Südwestfalen (Iserlohn)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'naturwissenschaftlich-technische akademie isny', label: 'Naturwissenschaftlich-Technische Akademie Isny', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'ernst-abbe-fachhochschule jena', label: 'Ernst-Abbe-Fachhochschule Jena', state: 'Thürigen', status: 'staatlich' },
  { value: 'friedrich-schiller-universität jena', label: 'Friedrich-Schiller-Universität Jena', state: 'Thürigen', status: 'staatlich' },
  { value: 'hochschule kaiserslautern', label: 'Hochschule Kaiserslautern', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'technische universität kaiserslautern', label: 'Technische Universität Kaiserslautern', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'hochschule für musik karlsruhe', label: 'Hochschule für Musik Karlsruhe', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule karlsruhe – technik und wirtschaft', label: 'Hochschule Karlsruhe – Technik und Wirtschaft', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'karlshochschule international university (karlsruhe)', label: 'Karlshochschule International University (Karlsruhe)', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'karlsruher institut für technologie', label: 'Karlsruher Institut für Technologie', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'pädagogische hochschule karlsruhe', label: 'Pädagogische Hochschule Karlsruhe', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'staatliche akademie der bildenden künste karlsruhe', label: 'Staatliche Akademie der Bildenden Künste Karlsruhe', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'staatliche hochschule für gestaltung karlsruhe', label: 'Staatliche Hochschule für Gestaltung Karlsruhe', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'cvjm-hochschule (kassel)', label: 'CVJM-Hochschule (Kassel)', state: 'Hessen', status: 'privat' },
  { value: 'kunsthochschule kassel', label: 'Kunsthochschule Kassel', state: 'Hessen', status: 'staatlich' },
  { value: 'universität kassel', label: 'Universität Kassel', state: 'Hessen', status: 'staatlich' },
  { value: 'hochschule für öffentliche verwaltung kehl', label: 'Hochschule für öffentliche Verwaltung Kehl', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule für angewandte wissenschaften kempten', label: 'Hochschule für angewandte Wissenschaften Kempten', state: 'Bayern', status: 'staatlich' },
  { value: 'christian-albrechts-universität zu kiel', label: 'Christian-Albrechts-Universität zu Kiel', state: 'Schleswig-Holstein', status: 'staatlich' },
  { value: 'fachhochschule kiel', label: 'Fachhochschule Kiel', state: 'Schleswig-Holstein', status: 'staatlich' },
  { value: 'muthesius kunsthochschule (kiel)', label: 'Muthesius Kunsthochschule (Kiel)', state: 'Schleswig-Holstein', status: 'staatlich' },
  { value: 'hochschule rhein-waal (kleve, kamp-lintfort)', label: 'Hochschule Rhein-Waal (Kleve, Kamp-Lintfort)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'hochschule koblenz', label: 'Hochschule Koblenz', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'universität koblenz-landau', label: 'Universität Koblenz-Landau', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'hochschule konstanz technik, wirtschaft und gestaltung', label: 'Hochschule Konstanz Technik, Wirtschaft und Gestaltung', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'universität konstanz', label: 'Universität Konstanz', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'cologne business school (köln)', label: 'Cologne Business School (Köln)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'deutsche sporthochschule köln', label: 'Deutsche Sporthochschule Köln', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'technische hochschule köln', label: 'Technische Hochschule Köln', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'hochschule für musik und tanz köln', label: 'Hochschule für Musik und Tanz Köln', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'katholische hochschule nordrhein-westfalen (köln, münster, paderborn, aachen)', label: 'Katholische Hochschule Nordrhein-Westfalen (Köln, Münster, Paderborn, Aachen)', state: 'Nordrhein-Westfalen', status: 'konfessionell' },
  { value: 'kunsthochschule für medien köln', label: 'Kunsthochschule für Medien Köln', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'universität zu köln', label: 'Universität zu Köln', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'rheinische fachhochschule köln', label: 'Rheinische Fachhochschule Köln', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'fachhochschule für finanzen brandenburg (königs wusterhausen)', label: 'Fachhochschule für Finanzen Brandenburg (Königs Wusterhausen)', state: 'Brandenburg', status: 'staatlich' },
  { value: 'wissenschaftliche hochschule lahr', label: 'Wissenschaftliche Hochschule Lahr', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'hochschule landshut', label: 'Hochschule Landshut', state: 'Bayern', status: 'staatlich' },
  { value: 'handelshochschule leipzig', label: 'Handelshochschule Leipzig', state: 'Sachsen', status: 'privat' },
  { value: 'hochschule für grafik und buchkunst leipzig', label: 'Hochschule für Grafik und Buchkunst Leipzig', state: 'Sachsen', status: 'staatlich' },
  { value: 'hochschule für musik und theater „felix mendelssohn bartholdy“ leipzig', label: 'Hochschule für Musik und Theater „Felix Mendelssohn Bartholdy“ Leipzig', state: 'Sachsen', status: 'staatlich' },
  { value: 'hochschule für technik, wirtschaft und kultur leipzig', label: 'Hochschule für Technik, Wirtschaft und Kultur Leipzig', state: 'Sachsen', status: 'staatlich' },
  { value: 'hochschule für telekommunikation leipzig', label: 'Hochschule für Telekommunikation Leipzig', state: 'Sachsen', status: 'privat' },
  { value: 'universität leipzig', label: 'Universität Leipzig', state: 'Sachsen', status: 'staatlich' },
  { value: 'hochschule ostwestfalen-lippe (lemgo)', label: 'Hochschule Ostwestfalen-Lippe (Lemgo)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'internationale hochschule liebenzell', label: 'Internationale Hochschule Liebenzell', state: 'Baden-Württemberg', status: 'konfessionell' },
  { value: 'akademie für darstellende kunst baden-württemberg (ludwigsburg)', label: 'Akademie für Darstellende Kunst Baden-Württemberg (Ludwigsburg)', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'filmakademie baden-württemberg (ludwigsburg)', label: 'Filmakademie Baden-Württemberg (Ludwigsburg)', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'evangelische hochschule ludwigsburg', label: 'Evangelische Hochschule Ludwigsburg', state: 'Baden-Württemberg', status: 'konfessionell' },
  { value: 'hochschule für öffentliche verwaltung und finanzen ludwigsburg', label: 'Hochschule für öffentliche Verwaltung und Finanzen Ludwigsburg', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'pädagogische hochschule ludwigsburg', label: 'Pädagogische Hochschule Ludwigsburg', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule ludwigshafen am rhein', label: 'Hochschule Ludwigshafen am Rhein', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'fachhochschule lübeck', label: 'Fachhochschule Lübeck', state: 'Schleswig-Holstein', status: 'staatlich' },
  { value: 'leuphana universität lüneburg', label: 'Leuphana Universität Lüneburg', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'musikhochschule lübeck', label: 'Musikhochschule Lübeck', state: 'Schleswig-Holstein', status: 'staatlich' },
  { value: 'universität zu lübeck', label: 'Universität zu Lübeck', state: 'Schleswig-Holstein', status: 'staatlich' },
  { value: 'otto-von-guericke-universität magdeburg', label: 'Otto-von-Guericke-Universität Magdeburg', state: 'Sachsen-Anhalt', status: 'staatlich' },
  { value: 'hochschule magdeburg-stendal', label: 'Hochschule Magdeburg-Stendal', state: 'Sachsen-Anhalt', status: 'staatlich' },
  { value: 'hochschule mainz', label: 'Hochschule Mainz', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'katholische hochschule mainz', label: 'Katholische Hochschule Mainz', state: 'Rheinland-Pfalz', status: 'konfessionell' },
  { value: 'johannes gutenberg-universität mainz', label: 'Johannes Gutenberg-Universität Mainz', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'hochschule der bundesagentur für arbeit (mannheim, schwerin)', label: 'Hochschule der Bundesagentur für Arbeit (Mannheim, Schwerin)', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule der wirtschaft für management mannheim', label: 'Hochschule der Wirtschaft für Management Mannheim', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'hochschule für musik und darstellende kunst mannheim', label: 'Hochschule für Musik und Darstellende Kunst Mannheim', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule mannheim', label: 'Hochschule Mannheim', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'popakademie baden-württemberg (mannheim)', label: 'Popakademie Baden-Württemberg (Mannheim)', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'universität mannheim', label: 'Universität Mannheim', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'archivschule marburg', label: 'Archivschule Marburg', state: 'Hessen', status: 'staatlich' },
  { value: 'evangelische hochschule tabor (marburg)', label: 'Evangelische Hochschule Tabor (Marburg)', state: 'Hessen', status: 'konfessionell' },
  { value: 'philipps-universität marburg', label: 'Philipps-Universität Marburg', state: 'Hessen', status: 'staatlich' },
  { value: 'hochschule für öffentliche verwaltung rheinland-pfalz (mayen, lautzenhausen)', label: 'Hochschule für öffentliche Verwaltung Rheinland-Pfalz (Mayen, Lautzenhausen)', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'fachhochschule für öffentliche verwaltung und rechtspflege meißen', label: 'Fachhochschule für öffentliche Verwaltung und Rechtspflege Meißen', state: 'Sachsen', status: 'staatlich' },
  { value: 'hochschule merseburg', label: 'Hochschule Merseburg', state: 'Sachsen-Anhalt', status: 'staatlich' },
  { value: 'hochschule mittweida', label: 'Hochschule Mittweida', state: 'Sachsen', status: 'staatlich' },
  { value: 'evangelische hochschule moritzburg', label: 'Evangelische Hochschule Moritzburg', state: 'Sachsen', status: 'konfessionell' },
  { value: 'hochschule ruhr west (mülheim, bottrop)', label: 'Hochschule Ruhr West (Mülheim, Bottrop)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'akademie der bildenden künste münchen', label: 'Akademie der Bildenden Künste München', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule für angewandte sprachen münchen', label: 'Hochschule für Angewandte Sprachen München', state: 'Bayern', status: 'privat' },
  { value: 'hochschule für angewandte wissenschaften münchen', label: 'Hochschule für angewandte Wissenschaften München', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule für fernsehen und film münchen', label: 'Hochschule für Fernsehen und Film München', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule für musik und theater münchen', label: 'Hochschule für Musik und Theater München', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule für philosophie münchen', label: 'Hochschule für Philosophie München', state: 'Bayern', status: 'konfessionell' },
  { value: 'hochschule für politik münchen', label: 'Hochschule für Politik München', state: 'Bayern', status: 'staatlich' },
  { value: 'fachhochschule für öffentliche verwaltung und rechtspflege in bayern (münchen)', label: 'Fachhochschule für öffentliche Verwaltung und Rechtspflege in Bayern (München)', state: 'Bayern', status: 'staatlich' },
  { value: 'katholische stiftungsfachhochschule münchen', label: 'Katholische Stiftungsfachhochschule München', state: 'Bayern', status: 'konfessionell' },
  { value: 'ludwig-maximilians-universität münchen', label: 'Ludwig-Maximilians-Universität München', state: 'Bayern', status: 'staatlich' },
  { value: 'macromedia hochschule für medien und kommunikation (münchen)', label: 'Macromedia Hochschule für Medien und Kommunikation (München)', state: 'Bayern', status: 'privat' },
  { value: 'munich business school (münchen)', label: 'Munich Business School (München)', state: 'Bayern', status: 'privat' },
  { value: 'technische universität münchen', label: 'Technische Universität München', state: 'Bayern', status: 'staatlich' },
  { value: 'ukrainische freie universität münchen', label: 'Ukrainische Freie Universität München', state: 'Bayern', status: 'privat' },
  { value: 'universität der bundeswehr münchen', label: 'Universität der Bundeswehr München', state: 'Bayern', status: 'staatlich' },
  { value: 'deutsche hochschule der polizei (münster)', label: 'Deutsche Hochschule der Polizei (Münster)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'fachhochschule münster', label: 'Fachhochschule Münster', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'kunstakademie münster', label: 'Kunstakademie Münster', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'philosophisch-theologische hochschule münster', label: 'Philosophisch-Theologische Hochschule Münster', state: 'Nordrhein-Westfalen', status: 'konfessionell' },
  { value: 'westfälische wilhelms-universität (münster)', label: 'Westfälische Wilhelms-Universität (Münster)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'hochschule für angewandte wissenschaften neu-ulm', label: 'Hochschule für angewandte Wissenschaften Neu-Ulm', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule neubrandenburg', label: 'Hochschule Neubrandenburg', state: 'Mecklenburg-Vorpommern', status: 'staatlich' },
  { value: 'augustana-hochschule neuendettelsau', label: 'Augustana-Hochschule Neuendettelsau', state: 'Bayern', status: 'konfessionell' },
  { value: 'rheinische fachhochschule neuss für internationale wirtschaft', label: 'Rheinische Fachhochschule Neuss für Internationale Wirtschaft', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'hochschule niederrhein (krefeld/mönchengladbach)', label: 'Hochschule Niederrhein (Krefeld/Mönchengladbach)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'fachhochschule nordhausen', label: 'Fachhochschule Nordhausen', state: 'Thürigen', status: 'staatlich' },
  { value: 'fachhochschule für finanzen nordrhein-westfalen (nordkirchen)', label: 'Fachhochschule für Finanzen Nordrhein-Westfalen (Nordkirchen)', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'akademie der bildenden künste nürnberg', label: 'Akademie der Bildenden Künste Nürnberg', state: 'Bayern', status: 'staatlich' },
  { value: 'evangelische hochschule nürnberg', label: 'Evangelische Hochschule Nürnberg', state: 'Bayern', status: 'konfessionell' },
  { value: 'hochschule für musik nürnberg', label: 'Hochschule für Musik Nürnberg', state: 'Bayern', status: 'staatlich' },
  { value: 'technische hochschule nürnberg georg simon ohm', label: 'Technische Hochschule Nürnberg Georg Simon Ohm', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule für kunsttherapie nürtingen', label: 'Hochschule für Kunsttherapie Nürtingen', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'hochschule für wirtschaft und umwelt nürtingen-geislingen', label: 'Hochschule für Wirtschaft und Umwelt Nürtingen-Geislingen', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'lutherische theologische hochschule oberursel', label: 'Lutherische Theologische Hochschule Oberursel', state: 'Hessen', status: 'konfessionell' },
  { value: 'hochschule für gestaltung offenbach am main', label: 'Hochschule für Gestaltung Offenbach am Main', state: 'Hessen', status: 'staatlich' },
  { value: 'hochschule offenburg', label: 'Hochschule Offenburg', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'carl von ossietzky universität oldenburg', label: 'Carl von Ossietzky Universität Oldenburg', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'fachhochschule der polizei des landes brandenburg (oranienburg)', label: 'Fachhochschule der Polizei des Landes Brandenburg (Oranienburg)', state: 'Brandenburg', status: 'staatlich' },
  { value: 'hochschule osnabrück', label: 'Hochschule Osnabrück', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'universität osnabrück', label: 'Universität Osnabrück', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'hochschule für künste im sozialen ottersberg', label: 'Hochschule für Künste im Sozialen Ottersberg', state: 'Niedersachsen', status: 'privat' },
  { value: 'fachhochschule der wirtschaft (paderborn)', label: 'Fachhochschule der Wirtschaft (Paderborn)', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'theologische fakultät paderborn', label: 'Theologische Fakultät Paderborn', state: 'Nordrhein-Westfalen', status: 'konfessionell' },
  { value: 'universität paderborn', label: 'Universität Paderborn', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'universität passau', label: 'Universität Passau', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule pforzheim', label: 'Hochschule Pforzheim', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'fachhochschule für sport & management potsdam', label: 'Fachhochschule für Sport & Management Potsdam', state: 'Brandenburg', status: 'privat' },
  { value: 'fachhochschule potsdam', label: 'Fachhochschule Potsdam', state: 'Brandenburg', status: 'staatlich' },
  { value: 'filmuniversität babelsberg (potsdam)', label: 'Filmuniversität Babelsberg (Potsdam)', state: 'Brandenburg', status: 'staatlich' },
  { value: 'universität potsdam', label: 'Universität Potsdam', state: 'Brandenburg', status: 'staatlich' },
  { value: 'hochschule ravensburg-weingarten', label: 'Hochschule Ravensburg-Weingarten', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule für katholische kirchenmusik und musikpädagogik regensburg', label: 'Hochschule für Katholische Kirchenmusik und Musikpädagogik Regensburg', state: 'Bayern', status: 'konfessionell' },
  { value: 'universität regensburg', label: 'Universität Regensburg', state: 'Bayern', status: 'staatlich' },
  { value: 'ostbayerische technische hochschule regensburg', label: 'Ostbayerische Technische Hochschule Regensburg', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule reutlingen', label: 'Hochschule Reutlingen', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'theologische hochschule reutlingen', label: 'Theologische Hochschule Reutlingen', state: 'Baden-Württemberg', status: 'konfessionell' },
  { value: 'mathias hochschule rheine', label: 'Mathias Hochschule Rheine', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'srh fernhochschule riedlingen', label: 'SRH Fernhochschule Riedlingen', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'technische hochschule rosenheim', label: 'Technische Hochschule Rosenheim', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule für musik und theater rostock', label: 'Hochschule für Musik und Theater Rostock', state: 'Mecklenburg-Vorpommern', status: 'staatlich' },
  { value: 'universität rostock', label: 'Universität Rostock', state: 'Mecklenburg-Vorpommern', status: 'staatlich' },
  { value: 'hessische hochschule für finanzen und rechtspflege (rotenburg an der fulda)', label: 'Hessische Hochschule für Finanzen und Rechtspflege (Rotenburg an der Fulda)', state: 'Hessen', status: 'staatlich' },
  { value: 'hochschule der sächsischen polizei (fh) (rothenburg/oberlausitz)', label: 'Hochschule der Sächsischen Polizei (FH) (Rothenburg/Oberlausitz)', state: 'Sachsen', status: 'staatlich' },
  { value: 'hochschule für forstwirtschaft rottenburg', label: 'Hochschule für Forstwirtschaft Rottenburg', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'katholische hochschule für kirchenmusik rottenburg', label: 'Katholische Hochschule für Kirchenmusik Rottenburg', state: 'Baden-Württemberg', status: 'konfessionell' },
  { value: 'deutsche hochschule für prävention und gesundheitsmanagement (saarbrücken)', label: 'Deutsche Hochschule für Prävention und Gesundheitsmanagement (Saarbrücken)', state: 'Saarland', status: 'privat' },
  { value: 'fachhochschule für verwaltung des saarlandes (saarbrücken)', label: 'Fachhochschule für Verwaltung des Saarlandes (Saarbrücken)', state: 'Saarland', status: 'staatlich' },
  { value: 'hochschule der bildenden künste saar (saarbrücken)', label: 'Hochschule der Bildenden Künste Saar (Saarbrücken)', state: 'Saarland', status: 'staatlich' },
  { value: 'hochschule für musik saar (saarbrücken)', label: 'Hochschule für Musik Saar (Saarbrücken)', state: 'Saarland', status: 'staatlich' },
  { value: 'hochschule für technik und wirtschaft des saarlandes (saarbrücken)', label: 'Hochschule für Technik und Wirtschaft des Saarlandes (Saarbrücken)', state: 'Saarland', status: 'staatlich' },
  { value: 'universität des saarlandes (saarbrücken, homburg)', label: 'Universität des Saarlandes (Saarbrücken, Homburg)', state: 'Saarland', status: 'staatlich' },
  { value: 'fachhochschule schmalkalden', label: 'Fachhochschule Schmalkalden', state: 'Thürigen', status: 'staatlich' },
  { value: 'hochschule für gestaltung schwäbisch gmünd', label: 'Hochschule für Gestaltung Schwäbisch Gmünd', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'fachhochschule schwetzingen', label: 'Fachhochschule Schwetzingen', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'pädagogische hochschule schwäbisch gmünd', label: 'Pädagogische Hochschule Schwäbisch Gmünd', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'universität siegen', label: 'Universität Siegen', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'deutsche universität für verwaltungswissenschaften speyer', label: 'Deutsche Universität für Verwaltungswissenschaften Speyer', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'philosophisch-theologische hochschule svd st. augustin', label: 'Philosophisch-Theologische Hochschule SVD St. Augustin', state: 'Nordrhein-Westfalen', status: 'konfessionell' },
  { value: 'fachhochschule stralsund', label: 'Fachhochschule Stralsund', state: 'Mecklenburg-Vorpommern', status: 'staatlich' },
  { value: 'akad bildungsgesellschaft (stuttgart)', label: 'AKAD Bildungsgesellschaft (Stuttgart)', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'duale hochschule baden-württemberg (stuttgart)', label: 'Duale Hochschule Baden-Württemberg (Stuttgart)', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'freie hochschule stuttgart', label: 'Freie Hochschule Stuttgart', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'hochschule der medien (stuttgart)', label: 'Hochschule der Medien (Stuttgart)', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule für musik und darstellende kunst stuttgart', label: 'Hochschule für Musik und Darstellende Kunst Stuttgart', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule für technik stuttgart', label: 'Hochschule für Technik Stuttgart', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'merz akademie (stuttgart)', label: 'Merz Akademie (Stuttgart)', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'staatliche akademie der bildenden künste stuttgart', label: 'Staatliche Akademie der Bildenden Künste Stuttgart', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'vwa hochschule für berufsbegleitendes studium stuttgart', label: 'VWA Hochschule für berufsbegleitendes Studium Stuttgart', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'universität hohenheim (stuttgart)', label: 'Universität Hohenheim (Stuttgart)', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'universität stuttgart', label: 'Universität Stuttgart', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule trier', label: 'Hochschule Trier', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'theologische fakultät trier', label: 'Theologische Fakultät Trier', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'universität trier', label: 'Universität Trier', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'hochschule für musik trossingen', label: 'Hochschule für Musik Trossingen', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'eberhard karls universität tübingen', label: 'Eberhard Karls Universität Tübingen', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'evangelische hochschule für kirchenmusik tübingen', label: 'Evangelische Hochschule für Kirchenmusik Tübingen', state: 'Baden-Württemberg', status: 'konfessionell' },
  { value: 'hochschule ulm', label: 'Hochschule Ulm', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'universität ulm', label: 'Universität Ulm', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'philosophisch-theologische hochschule vallendar', label: 'Philosophisch-Theologische Hochschule Vallendar', state: 'Rheinland-Pfalz', status: 'konfessionell' },
  { value: 'whu – otto beisheim school of management (vallendar)', label: 'WHU – Otto Beisheim School of Management (Vallendar)', state: 'Rheinland-Pfalz', status: 'privat' },
  { value: 'fachhochschule für wirtschaft und technik vechta/diepholz/oldenburg', label: 'Fachhochschule für Wirtschaft und Technik Vechta/Diepholz/Oldenburg', state: 'Niedersachsen', status: 'privat' },
  { value: 'universität vechta', label: 'Universität Vechta', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'hochschule für polizei baden-württemberg', label: 'Hochschule für Polizei Baden-Württemberg', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'fachhochschule wedel', label: 'Fachhochschule Wedel', state: 'Schleswig-Holstein', status: 'privat' },
  { value: 'hochschule weihenstephan-triesdorf', label: 'Hochschule Weihenstephan-Triesdorf', state: 'Bayern', status: 'staatlich' },
  { value: 'gustav-siewerth-akademie (weilheim)', label: 'Gustav-Siewerth-Akademie (Weilheim)', state: 'Baden-Württemberg', status: 'privat' },
  { value: 'bauhaus-universität weimar', label: 'Bauhaus-Universität Weimar', state: 'Thürigen', status: 'staatlich' },
  { value: 'hochschule für musik franz liszt weimar', label: 'Hochschule für Musik Franz Liszt Weimar', state: 'Thürigen', status: 'staatlich' },
  { value: 'pädagogische hochschule weingarten', label: 'Pädagogische Hochschule Weingarten', state: 'Baden-Württemberg', status: 'staatlich' },
  { value: 'hochschule harz (wernigerode und halberstadt)', label: 'Hochschule Harz (Wernigerode und Halberstadt)', state: 'Sachsen-Anhalt', status: 'staatlich' },
  { value: 'ebs universität für wirtschaft und recht (wiesbaden, oestrich-winkel)', label: 'EBS Universität für Wirtschaft und Recht (Wiesbaden, Oestrich-Winkel)', state: 'Hessen', status: 'privat' },
  { value: 'hessische hochschule für polizei und verwaltung (wiesbaden)', label: 'Hessische Hochschule für Polizei und Verwaltung (Wiesbaden)', state: 'Hessen', status: 'staatlich' },
  { value: 'hochschule rheinmain (wiesbaden und rüsselsheim)', label: 'Hochschule RheinMain (Wiesbaden und Rüsselsheim)', state: 'Hessen', status: 'staatlich' },
  { value: 'wilhelm büchner hochschule (pfungstadt)', label: 'Wilhelm Büchner Hochschule (Pfungstadt)', state: 'Hessen', status: 'privat' },
  { value: 'technische hochschule wildau (fh)', label: 'Technische Hochschule Wildau (FH)', state: 'Brandenburg', status: 'staatlich' },
  { value: 'jade hochschule (wilhelmshaven, oldenburg, elsfleth)', label: 'Jade Hochschule (Wilhelmshaven, Oldenburg, Elsfleth)', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'hochschule wismar', label: 'Hochschule Wismar', state: 'Mecklenburg-Vorpommern', status: 'staatlich' },
  { value: 'universität witten/herdecke', label: 'Universität Witten/Herdecke', state: 'Nordrhein-Westfalen', status: 'privat' },
  { value: 'ostfalia hochschule für angewandte wissenschaften (wolfenbüttel, salzgitter, wolfsburg, suderburg)', label: 'Ostfalia Hochschule für angewandte Wissenschaften (Wolfenbüttel, Salzgitter, Wolfsburg, Suderburg)', state: 'Niedersachsen', status: 'staatlich' },
  { value: 'hochschule worms', label: 'Hochschule Worms', state: 'Rheinland-Pfalz', status: 'staatlich' },
  { value: 'bergische universität wuppertal', label: 'Bergische Universität Wuppertal', state: 'Nordrhein-Westfalen', status: 'staatlich' },
  { value: 'kirchliche hochschule wuppertal/bethel', label: 'Kirchliche Hochschule Wuppertal/Bethel', state: 'Nordrhein-Westfalen', status: 'konfessionell' },
  { value: 'hochschule für angewandte wissenschaften würzburg-schweinfurt', label: 'Hochschule für angewandte Wissenschaften Würzburg-Schweinfurt', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule für musik würzburg', label: 'Hochschule für Musik Würzburg', state: 'Bayern', status: 'staatlich' },
  { value: 'julius-maximilians-universität würzburg', label: 'Julius-Maximilians-Universität Würzburg', state: 'Bayern', status: 'staatlich' },
  { value: 'hochschule zittau/görlitz', label: 'Hochschule Zittau/Görlitz', state: 'Sachsen', status: 'staatlich' },
  { value: 'dpfa hochschule sachsen (zwickau)', label: 'DPFA Hochschule Sachsen (Zwickau)', state: 'Sachsen', status: 'privat' },
  { value: 'nbs northern business school – hochschule für management und sicherheit', label: 'NBS Northern Business School – Hochschule für Management und Sicherheit', state: 'Hamburg', status: 'privat' },
  { value: 'westsächsische hochschule zwickau', label: 'Westsächsische Hochschule Zwickau', state: 'Sachsen', status: 'staatlich' },
]



export const cities = [
    { value: 'berlin', label: 'Berlin', state: 'Berlin' },
    {value: 'hamburg', label: 'Hamburg', state: 'Hamburg'},
    {value: 'münchen', label: 'München', state: 'Bayern'},
    {value: 'köln', label: 'Köln', state: 'Nordrhein-Westfalen'},
    {value: 'frankfurt am main', label: 'Frankfurt am Main', state: 'Hessen'},
    {value: 'stuttgart', label: 'Stuttgart', state: 'Baden-Württemberg'},
    {value: 'düsseldorf', label: 'Düsseldorf', state: 'Nordrhein-Westfalen'},
    {value: 'dortmund', label: 'Dortmund', state: 'Nordrhein-Westfalen'},
    {value: 'essen', label: 'Essen', state: 'Nordrhein-Westfalen'},
    {value: 'leipzig', label: 'Leipzig', state: 'Sachsen'},
    {value: 'bremen', label: 'Bremen', state: 'Bremen'},
    {value: 'dresden', label: 'Dresden', state: 'Sachsen'},
    {value: 'hannover', label: 'Hannover', state: 'Niedersachsen'},
    {value: 'nürnberg', label: 'Nürnberg', state: 'Bayern'},
    {value: 'duisburg', label: 'Duisburg', state: 'Nordrhein-Westfalen'},
    {value: 'bochum', label: 'Bochum', state: 'Nordrhein-Westfalen'},
    {value: 'wuppertal', label: 'Wuppertal', state: 'Nordrhein-Westfalen'},
    {value: 'bielefeld', label: 'Bielefeld', state: 'Nordrhein-Westfalen'},
    {value: 'bonn', label: 'Bonn', state: 'Nordrhein-Westfalen'},
    {value: 'münster', label: 'Münster', state: 'Nordrhein-Westfalen'},
    {value: 'karlsruhe', label: 'Karlsruhe', state: 'Baden-Württemberg'},
    {value: 'mannheim', label: 'Mannheim', state: 'Baden-Württemberg'},
    {value: 'augsburg', label: 'Augsburg', state: 'Bayern'},
    {value: 'wiesbaden', label: 'Wiesbaden', state: 'Hessen'},
    {value: 'mönchengladbach', label: 'Mönchengladbach', state: 'Nordrhein-Westfalen'},
    {value: 'gelsenkirchen', label: 'Gelsenkirchen', state: 'Nordrhein-Westfalen'},
    {value: 'braunschweig', label: 'Braunschweig', state: 'Niedersachsen'},
    {value: 'kiel', label: 'Kiel', state: 'Schleswig-Holstein'},
    {value: 'chemnitz', label: 'Chemnitz', state: 'Sachsen'},
    {value: 'aachen', label: 'Aachen', state: 'Nordrhein-Westfalen'},
    {value: 'halle (saale)', label: 'Halle (Saale)', state: 'Sachsen-Anhalt'},
    {value: 'magdeburg', label: 'Magdeburg', state: 'Sachsen-Anhalt'},
    {value: 'freiburg im breisgau', label: 'Freiburg im Breisgau', state: 'Baden-Württemberg'},
    {value: 'krefeld', label: 'Krefeld', state: 'Nordrhein-Westfalen'},
    {value: 'lübeck', label: 'Lübeck', state: 'Schleswig-Holstein'},
    {value: 'mainz', label: 'Mainz', state: 'Rheinland-Pfalz'},
    {value: 'erfurt', label: 'Erfurt', state: 'Thüringen'},
    {value: 'oberhausen', label: 'Oberhausen', state: 'Nordrhein-Westfalen'},
    {value: 'rostock', label: 'Rostock', state: 'Mecklenburg-Vorpommern'},
    {value: 'kassel', label: 'Kassel', state: 'Hessen'},
    {value: 'hagen', label: 'Hagen', state: 'Nordrhein-Westfalen'},
    {value: 'saarbrücken', label: 'Saarbrücken', state: 'Saarland'},
    {value: 'hamm', label: 'Hamm', state: 'Nordrhein-Westfalen'},
    {value: 'potsdam', label: 'Potsdam', state: 'Brandenburg'},
    {value: 'mülheim an der ruhr', label: 'Mülheim an der Ruhr', state: 'Nordrhein-Westfalen'},
    {value: 'ludwigshafen am rhein', label: 'Ludwigshafen am Rhein', state: 'Rheinland-Pfalz'},
    {value: 'oldenburg', label: 'Oldenburg', state: 'Niedersachsen'},
    {value: 'osnabrück', label: 'Osnabrück', state: 'Niedersachsen'},
    {value: 'leverkusen', label: 'Leverkusen', state: 'Nordrhein-Westfalen'},
    {value: 'heidelberg', label: 'Heidelberg', state: 'Baden-Württemberg'},
    {value: 'solingen', label: 'Solingen', state: 'Nordrhein-Westfalen'},
    {value: 'darmstadt', label: 'Darmstadt', state: 'Hessen'},
    {value: 'herne', label: 'Herne', state: 'Nordrhein-Westfalen'},
    {value: 'neuss', label: 'Neuss', state: 'Nordrhein-Westfalen'},
    {value: 'regensburg', label: 'Regensburg', state: 'Bayern'},
    {value: 'paderborn', label: 'Paderborn', state: 'Nordrhein-Westfalen'},
    {value: 'ingolstadt', label: 'Ingolstadt', state: 'Bayern'},
    {value: 'offenbach am main', label: 'Offenbach am Main', state: 'Hessen'},
    {value: 'würzburg', label: 'Würzburg', state: 'Bayern'},
    {value: 'fürth', label: 'Fürth', state: 'Bayern'},
    {value: 'ulm', label: 'Ulm', state: 'Baden-Württemberg'},
    {value: 'heilbronn', label: 'Heilbronn', state: 'Baden-Württemberg'},
    {value: 'pforzheim', label: 'Pforzheim', state: 'Baden-Württemberg'},
    {value: 'wolfsburg', label: 'Wolfsburg', state: 'Niedersachsen'},
    {value: 'göttingen', label: 'Göttingen', state: 'Niedersachsen'},
    {value: 'bottrop', label: 'Bottrop', state: 'Nordrhein-Westfalen'},
    {value: 'reutlingen', label: 'Reutlingen', state: 'Baden-Württemberg'},
    {value: 'koblenz', label: 'Koblenz', state: 'Rheinland-Pfalz'},
    {value: 'recklinghausen', label: 'Recklinghausen', state: 'Nordrhein-Westfalen'},
    {value: 'bremerhaven', label: 'Bremerhaven', state: 'Bremen'},
    {value: 'bergisch gladbach', label: 'Bergisch Gladbach', state: 'Nordrhein-Westfalen'},
    {value: 'jena', label: 'Jena', state: 'Thüringen'},
    {value: 'erlangen', label: 'Erlangen', state: 'Bayern'},
    {value: 'remscheid', label: 'Remscheid', state: 'Nordrhein-Westfalen'},
    {value: 'trier', label: 'Trier', state: 'Rheinland-Pfalz'},
    {value: 'salzgitter', label: 'Salzgitter', state: 'Niedersachsen'},
    {value: 'moers', label: 'Moers', state: 'Nordrhein-Westfalen'},
    {value: 'siegen', label: 'Siegen', state: 'Nordrhein-Westfalen'},
    {value: 'hildesheim', label: 'Hildesheim', state: 'Niedersachsen'},
    {value: 'cottbus', label: 'Cottbus', state: 'Brandenburg'},
    {value: 'kaiserslautern', label: 'Kaiserslautern', state: 'Rheinland-Pfalz'},
    {value: 'gütersloh', label: 'Gütersloh', state: 'Nordrhein-Westfalen'},
    {value: 'witten', label: 'Witten', state: 'Nordrhein-Westfalen'},
    {value: 'hanau', label: 'Hanau', state: 'Hessen'},
    {value: 'schwerin', label: 'Schwerin', state: 'Mecklenburg-Vorpommern'},
    {value: 'gera', label: 'Gera', state: 'Thüringen'},
    {value: 'ludwigsburg', label: 'Ludwigsburg', state: 'Baden-Württemberg'},
    {value: 'esslingen am neckar', label: 'Esslingen am Neckar', state: 'Baden-Württemberg'},
    {value: 'iserlohn', label: 'Iserlohn', state: 'Nordrhein-Westfalen'},
    {value: 'düren', label: 'Düren', state: 'Nordrhein-Westfalen'},
    {value: 'zwickau', label: 'Zwickau', state: 'Sachsen'},
    {value: 'tübingen', label: 'Tübingen', state: 'Baden-Württemberg'},
    {value: 'flensburg', label: 'Flensburg', state: 'Schleswig-Holstein'},
    {value: 'gießen', label: 'Gießen', state: 'Hessen'},
    {value: 'ratingen', label: 'Ratingen', state: 'Nordrhein-Westfalen'},
    {value: 'lünen', label: 'Lünen', state: 'Nordrhein-Westfalen'},
    {value: 'villingen-schwenningen', label: 'Villingen-Schwenningen', state: 'Baden-Württemberg'},
    {value: 'konstanz', label: 'Konstanz', state: 'Baden-Württemberg'},
    {value: 'marl', label: 'Marl', state: 'Nordrhein-Westfalen'},
    {value: 'worms', label: 'Worms', state: 'Rheinland-Pfalz'},
    {value: 'dessau-roßlau', label: 'Dessau-Roßlau', state: 'Sachsen-Anhalt'},
    {value: 'velbert', label: 'Velbert', state: 'Nordrhein-Westfalen'},
    {value: 'minden', label: 'Minden', state: 'Nordrhein-Westfalen'},
    {value: 'neumünster', label: 'Neumünster', state: 'Schleswig-Holstein'},
    {value: 'norderstedt', label: 'Norderstedt', state: 'Schleswig-Holstein'},
    {value: 'delmenhorst', label: 'Delmenhorst', state: 'Niedersachsen'},
    {value: 'bamberg', label: 'Bamberg', state: 'Bayern'},
    {value: 'viersen', label: 'Viersen', state: 'Nordrhein-Westfalen'},
    {value: 'wilhelmshaven', label: 'Wilhelmshaven', state: 'Niedersachsen'},
    {value: 'marburg', label: 'Marburg', state: 'Hessen'},
    {value: 'rheine', label: 'Rheine', state: 'Nordrhein-Westfalen'},
    {value: 'gladbeck', label: 'Gladbeck', state: 'Nordrhein-Westfalen'},
    {value: 'dorsten', label: 'Dorsten', state: 'Nordrhein-Westfalen'},
    {value: 'lüneburg', label: 'Lüneburg', state: 'Niedersachsen'},
    {value: 'troisdorf', label: 'Troisdorf', state: 'Nordrhein-Westfalen'},
    {value: 'detmold', label: 'Detmold', state: 'Nordrhein-Westfalen'},
    {value: 'bayreuth', label: 'Bayreuth', state: 'Bayern'},
    {value: 'castrop-rauxel', label: 'Castrop-Rauxel', state: 'Nordrhein-Westfalen'},
    {value: 'arnsberg', label: 'Arnsberg', state: 'Nordrhein-Westfalen'},
    {value: 'lüdenscheid', label: 'Lüdenscheid', state: 'Nordrhein-Westfalen'},
    {value: 'brandenburg an der havel', label: 'Brandenburg an der Havel', state: 'Brandenburg'},
    {value: 'landshut', label: 'Landshut', state: 'Bayern'},
    {value: 'bocholt', label: 'Bocholt', state: 'Nordrhein-Westfalen'},
    {value: 'aschaffenburg', label: 'Aschaffenburg', state: 'Bayern'},
    {value: 'celle', label: 'Celle', state: 'Niedersachsen'},
    {value: 'kempten (allgäu)', label: 'Kempten (Allgäu)', state: 'Bayern'},
    {value: 'fulda', label: 'Fulda', state: 'Hessen'},
    {value: 'lippstadt', label: 'Lippstadt', state: 'Nordrhein-Westfalen'},
    {value: 'aalen', label: 'Aalen', state: 'Baden-Württemberg'},
    {value: 'dinslaken', label: 'Dinslaken', state: 'Nordrhein-Westfalen'},
    {value: 'herford', label: 'Herford', state: 'Nordrhein-Westfalen'},
    {value: 'kerpen', label: 'Kerpen', state: 'Nordrhein-Westfalen'},
    {value: 'plauen', label: 'Plauen', state: 'Sachsen'},
    {value: 'rüsselsheim am main', label: 'Rüsselsheim am Main', state: 'Hessen'},
    {value: 'neuwied', label: 'Neuwied', state: 'Rheinland-Pfalz'},
    {value: 'sindelfingen', label: 'Sindelfingen', state: 'Baden-Württemberg'},
    {value: 'weimar', label: 'Weimar', state: 'Thüringen'},
    {value: 'neubrandenburg', label: 'Neubrandenburg', state: 'Mecklenburg-Vorpommern'},
    {value: 'dormagen', label: 'Dormagen', state: 'Nordrhein-Westfalen'},
    {value: 'grevenbroich', label: 'Grevenbroich', state: 'Nordrhein-Westfalen'},
    {value: 'rosenheim', label: 'Rosenheim', state: 'Bayern'},
    {value: 'herten', label: 'Herten', state: 'Nordrhein-Westfalen'},
    {value: 'bergheim', label: 'Bergheim', state: 'Nordrhein-Westfalen'},
    {value: 'schwäbisch gmünd', label: 'Schwäbisch Gmünd', state: 'Baden-Württemberg'},
    {value: 'garbsen', label: 'Garbsen', state: 'Niedersachsen'},
    {value: 'wesel', label: 'Wesel', state: 'Nordrhein-Westfalen'},
    {value: 'friedrichshafen', label: 'Friedrichshafen', state: 'Baden-Württemberg'},
    {value: 'hürth', label: 'Hürth', state: 'Nordrhein-Westfalen'},
    {value: 'stralsund', label: 'Stralsund', state: 'Mecklenburg-Vorpommern'},
    {value: 'offenburg', label: 'Offenburg', state: 'Baden-Württemberg'},
    {value: 'greifswald', label: 'Greifswald', state: 'Mecklenburg-Vorpommern'},
    {value: 'langenfeld (rheinland)', label: 'Langenfeld (Rheinland)', state: 'Nordrhein-Westfalen'},
    {value: 'frankfurt (oder)', label: 'Frankfurt (Oder)', state: 'Brandenburg'},
    {value: 'neu-ulm', label: 'Neu-Ulm', state: 'Bayern'},
    {value: 'euskirchen', label: 'Euskirchen', state: 'Nordrhein-Westfalen'},
    {value: 'hameln', label: 'Hameln', state: 'Niedersachsen'},
    {value: 'unna', label: 'Unna', state: 'Nordrhein-Westfalen'},
    {value: 'göppingen', label: 'Göppingen', state: 'Baden-Württemberg'},
    {value: 'stolberg (rheinland)', label: 'Stolberg (Rheinland)', state: 'Nordrhein-Westfalen'},
    {value: 'görlitz', label: 'Görlitz', state: 'Sachsen'},
    {value: 'eschweiler', label: 'Eschweiler', state: 'Nordrhein-Westfalen'},
    {value: 'sankt augustin', label: 'Sankt Augustin', state: 'Nordrhein-Westfalen'},
    {value: 'hilden', label: 'Hilden', state: 'Nordrhein-Westfalen'},
    {value: 'meerbusch', label: 'Meerbusch', state: 'Nordrhein-Westfalen'},
    {value: 'waiblingen', label: 'Waiblingen', state: 'Baden-Württemberg'},
    {value: 'baden-baden', label: 'Baden-Baden', state: 'Baden-Württemberg'},
    {value: 'hattingen', label: 'Hattingen', state: 'Nordrhein-Westfalen'},
    {value: 'lingen (ems)', label: 'Lingen (Ems)', state: 'Niedersachsen'},
    {value: 'pulheim', label: 'Pulheim', state: 'Nordrhein-Westfalen'},
    {value: 'bad homburg vor der höhe', label: 'Bad Homburg vor der Höhe', state: 'Hessen'},
    {value: 'bad salzuflen', label: 'Bad Salzuflen', state: 'Nordrhein-Westfalen'},
    {value: 'langenhagen', label: 'Langenhagen', state: 'Niedersachsen'},
    {value: 'schweinfurt', label: 'Schweinfurt', state: 'Bayern'},
    {value: 'neustadt an der weinstraße', label: 'Neustadt an der Weinstraße', state: 'Rheinland-Pfalz'},
    {value: 'nordhorn', label: 'Nordhorn', state: 'Niedersachsen'},
    {value: 'menden (sauerland)', label: 'Menden (Sauerland)', state: 'Nordrhein-Westfalen'},
    {value: 'wetzlar', label: 'Wetzlar', state: 'Hessen'},
    {value: 'ahlen', label: 'Ahlen', state: 'Nordrhein-Westfalen'},
    {value: 'wolfenbüttel', label: 'Wolfenbüttel', state: 'Niedersachsen'},
    {value: 'frechen', label: 'Frechen', state: 'Nordrhein-Westfalen'},
    {value: 'ibbenbüren', label: 'Ibbenbüren', state: 'Nordrhein-Westfalen'},
    {value: 'passau', label: 'Passau', state: 'Bayern'},
    {value: 'kleve', label: 'Kleve', state: 'Nordrhein-Westfalen'},
    {value: 'willich', label: 'Willich', state: 'Nordrhein-Westfalen'},
    {value: 'goslar', label: 'Goslar', state: 'Niedersachsen'},
    {value: 'speyer', label: 'Speyer', state: 'Rheinland-Pfalz'},
    {value: 'emden', label: 'Emden', state: 'Niedersachsen'},
    {value: 'gummersbach', label: 'Gummersbach', state: 'Nordrhein-Westfalen'},
    {value: 'bad kreuznach', label: 'Bad Kreuznach', state: 'Rheinland-Pfalz'},
    {value: 'ravensburg', label: 'Ravensburg', state: 'Baden-Württemberg'},
    {value: 'böblingen', label: 'Böblingen', state: 'Baden-Württemberg'},
    {value: 'peine', label: 'Peine', state: 'Niedersachsen'},
    {value: 'erftstadt', label: 'Erftstadt', state: 'Nordrhein-Westfalen'},
    {value: 'elmshorn', label: 'Elmshorn', state: 'Schleswig-Holstein'},
    {value: 'heidenheim an der brenz', label: 'Heidenheim an der Brenz', state: 'Baden-Württemberg'},
    {value: 'lörrach', label: 'Lörrach', state: 'Baden-Württemberg'},
    {value: 'rastatt', label: 'Rastatt', state: 'Baden-Württemberg'},
    {value: 'bergkamen', label: 'Bergkamen', state: 'Nordrhein-Westfalen'},
    {value: 'bad oeynhausen', label: 'Bad Oeynhausen', state: 'Nordrhein-Westfalen'},
    {value: 'rheda-wiedenbrück', label: 'Rheda-Wiedenbrück', state: 'Nordrhein-Westfalen'},
    {value: 'cuxhaven', label: 'Cuxhaven', state: 'Niedersachsen'},
    {value: 'frankenthal (pfalz)', label: 'Frankenthal (Pfalz)', state: 'Rheinland-Pfalz'},
    {value: 'freising', label: 'Freising', state: 'Bayern'},
    {value: 'leonberg', label: 'Leonberg', state: 'Baden-Württemberg'},
    {value: 'bornheim', label: 'Bornheim', state: 'Nordrhein-Westfalen'},
    {value: 'singen (hohentwiel)', label: 'Singen (Hohentwiel)', state: 'Baden-Württemberg'},
    {value: 'gronau (westf.)', label: 'Gronau (Westf.)', state: 'Nordrhein-Westfalen'},
    {value: 'straubing', label: 'Straubing', state: 'Bayern'},
    {value: 'soest', label: 'Soest', state: 'Nordrhein-Westfalen'},
    {value: 'stade', label: 'Stade', state: 'Niedersachsen'},
    {value: 'hennef (sieg)', label: 'Hennef (Sieg)', state: 'Nordrhein-Westfalen'},
    {value: 'dachau', label: 'Dachau', state: 'Bayern'},
    {value: 'alsdorf', label: 'Alsdorf', state: 'Nordrhein-Westfalen'},
    {value: 'neunkirchen', label: 'Neunkirchen', state: 'Saarland'},
    {value: 'schwerte', label: 'Schwerte', state: 'Nordrhein-Westfalen'},
    {value: 'dülmen', label: 'Dülmen', state: 'Nordrhein-Westfalen'},
    {value: 'herzogenrath', label: 'Herzogenrath', state: 'Nordrhein-Westfalen'},
    {value: 'melle', label: 'Melle', state: 'Niedersachsen'},
    {value: 'landau in der pfalz', label: 'Landau in der Pfalz', state: 'Rheinland-Pfalz'},
    {value: 'lutherstadt wittenberg', label: 'Lutherstadt Wittenberg', state: 'Sachsen-Anhalt'},
    {value: 'lahr/schwarzwald', label: 'Lahr/Schwarzwald', state: 'Baden-Württemberg'},
    {value: 'oberursel (taunus)', label: 'Oberursel (Taunus)', state: 'Hessen'},
    {value: 'hof', label: 'Hof', state: 'Bayern'},
    {value: 'filderstadt', label: 'Filderstadt', state: 'Baden-Württemberg'},
    {value: 'fellbach', label: 'Fellbach', state: 'Baden-Württemberg'},
    {value: 'bünde', label: 'Bünde', state: 'Nordrhein-Westfalen'},
    {value: 'gotha', label: 'Gotha', state: 'Thüringen'},
    {value: 'weinheim', label: 'Weinheim', state: 'Baden-Württemberg'},
    {value: 'albstadt', label: 'Albstadt', state: 'Baden-Württemberg'},
    {value: 'rodgau', label: 'Rodgau', state: 'Hessen'},
    {value: 'bruchsal', label: 'Bruchsal', state: 'Baden-Württemberg'},
    {value: 'erkrath', label: 'Erkrath', state: 'Nordrhein-Westfalen'},
    {value: 'brühl', label: 'Brühl', state: 'Nordrhein-Westfalen'},
    {value: 'oranienburg', label: 'Oranienburg', state: 'Brandenburg'},
    {value: 'neustadt am rübenberge', label: 'Neustadt am Rübenberge', state: 'Niedersachsen'},
    {value: 'lehrte', label: 'Lehrte', state: 'Niedersachsen'},
    {value: 'rottenburg am neckar', label: 'Rottenburg am Neckar', state: 'Baden-Württemberg'},
    {value: 'falkensee', label: 'Falkensee', state: 'Brandenburg'},
    {value: 'kaufbeuren', label: 'Kaufbeuren', state: 'Bayern'},
    {value: 'memmingen', label: 'Memmingen', state: 'Bayern'},
    {value: 'erkelenz', label: 'Erkelenz', state: 'Nordrhein-Westfalen'},
    {value: 'kamen', label: 'Kamen', state: 'Nordrhein-Westfalen'},
    {value: 'bietigheim-bissingen', label: 'Bietigheim-Bissingen', state: 'Baden-Württemberg'},
    {value: 'kaarst', label: 'Kaarst', state: 'Nordrhein-Westfalen'},
    {value: 'pinneberg', label: 'Pinneberg', state: 'Schleswig-Holstein'},
    {value: 'wismar', label: 'Wismar', state: 'Mecklenburg-Vorpommern'},
    {value: 'eisenach', label: 'Eisenach', state: 'Thüringen'},
    {value: 'weiden in der oberpfalz', label: 'Weiden in der Oberpfalz', state: 'Bayern'},
    {value: 'borken', label: 'Borken', state: 'Nordrhein-Westfalen'},
    {value: 'nettetal', label: 'Nettetal', state: 'Nordrhein-Westfalen'},
    {value: 'amberg', label: 'Amberg', state: 'Bayern'},
    {value: 'gifhorn', label: 'Gifhorn', state: 'Niedersachsen'},
    {value: 'nordhausen', label: 'Nordhausen', state: 'Thüringen'},
    {value: 'homburg', label: 'Homburg', state: 'Saarland'},
    {value: 'aurich', label: 'Aurich', state: 'Niedersachsen'},
    {value: 'heinsberg', label: 'Heinsberg', state: 'Nordrhein-Westfalen'},
    {value: 'ansbach', label: 'Ansbach', state: 'Bayern'},
    {value: 'dreieich', label: 'Dreieich', state: 'Hessen'},
    {value: 'wunstorf', label: 'Wunstorf', state: 'Niedersachsen'},
    {value: 'freiberg', label: 'Freiberg', state: 'Sachsen'},
    {value: 'laatzen', label: 'Laatzen', state: 'Niedersachsen'},
    {value: 'siegburg', label: 'Siegburg', state: 'Nordrhein-Westfalen'},
    {value: 'seevetal', label: 'Seevetal', state: 'Niedersachsen'},
    {value: 'coburg', label: 'Coburg', state: 'Bayern'},
    {value: 'königswinter', label: 'Königswinter', state: 'Nordrhein-Westfalen'},
    {value: 'nürtingen', label: 'Nürtingen', state: 'Baden-Württemberg'},
    {value: 'weißenfels', label: 'Weißenfels', state: 'Sachsen-Anhalt'},
    {value: 'halberstadt', label: 'Halberstadt', state: 'Sachsen-Anhalt'},
    {value: 'lemgo', label: 'Lemgo', state: 'Nordrhein-Westfalen'},
    {value: 'schwabach', label: 'Schwabach', state: 'Bayern'},
    {value: 'pirmasens', label: 'Pirmasens', state: 'Rheinland-Pfalz'},
    {value: 'monheim am rhein', label: 'Monheim am Rhein', state: 'Nordrhein-Westfalen'},
    {value: 'kirchheim unter teck', label: 'Kirchheim unter Teck', state: 'Baden-Württemberg'},
    {value: 'bensheim', label: 'Bensheim', state: 'Hessen'},
    {value: 'germering', label: 'Germering', state: 'Bayern'},
    {value: 'eberswalde', label: 'Eberswalde', state: 'Brandenburg'},
    {value: 'löhne', label: 'Löhne', state: 'Nordrhein-Westfalen'},
    {value: 'leinfelden-echterdingen', label: 'Leinfelden-Echterdingen', state: 'Baden-Württemberg'},
    {value: 'stendal', label: 'Stendal', state: 'Sachsen-Anhalt'},
    {value: 'neumarkt in der oberpfalz', label: 'Neumarkt in der Oberpfalz', state: 'Bayern'},
    {value: 'schwäbisch hall', label: 'Schwäbisch Hall', state: 'Baden-Württemberg'},
    {value: 'buxtehude', label: 'Buxtehude', state: 'Niedersachsen'},
    {value: 'hofheim am taunus', label: 'Hofheim am Taunus', state: 'Hessen'},
    {value: 'schorndorf', label: 'Schorndorf', state: 'Baden-Württemberg'},
    {value: 'hückelhoven', label: 'Hückelhoven', state: 'Nordrhein-Westfalen'},
    {value: 'bautzen', label: 'Bautzen', state: 'Sachsen'},
    {value: 'völklingen', label: 'Völklingen', state: 'Saarland'},
    {value: 'ettlingen', label: 'Ettlingen', state: 'Baden-Württemberg'},
    {value: 'freital', label: 'Freital', state: 'Sachsen'},
    {value: 'ostfildern', label: 'Ostfildern', state: 'Baden-Württemberg'},
    {value: 'ahaus', label: 'Ahaus', state: 'Nordrhein-Westfalen'},
    {value: 'bitterfeld-wolfen8', label: 'Bitterfeld-Wolfen8', state: 'Sachsen-Anhalt'},
    {value: 'buchholz in der nordheide', label: 'Buchholz in der Nordheide', state: 'Niedersachsen'},
    {value: 'würselen', label: 'Würselen', state: 'Nordrhein-Westfalen'},
    {value: 'maintal', label: 'Maintal', state: 'Hessen'},
    {value: 'mettmann', label: 'Mettmann', state: 'Nordrhein-Westfalen'},
    {value: 'pirna', label: 'Pirna', state: 'Sachsen'},
    {value: 'bernau bei berlin', label: 'Bernau bei Berlin', state: 'Brandenburg'},
    {value: 'niederkassel', label: 'Niederkassel', state: 'Nordrhein-Westfalen'},
    {value: 'haltern am see', label: 'Haltern am See', state: 'Nordrhein-Westfalen'},
]

export const states = [
    { value: 'baden-württemberg', label: 'Baden-Württemberg', state: 'Baden-Württemberg' },
    { value: 'bayern', label: 'Bayern', state: 'Bayern' },
    { value: 'berlin', label: 'Berlin', state: 'Berlin' },
    { value: 'brandenburg', label: 'Brandenburg', state: 'Brandenburg' },
    { value: 'bremen', label: 'Bremen', state: 'Baden-Württemberg' },
    { value: 'hamburg', label: 'Hamburg', state: 'Hamburg' },
    { value: 'hessen', label: 'Hessen', state: 'Hessen' },
    { value: 'mecklenburg-vorpommern', label: 'Mecklenburg-Vorpommern', state: 'Mecklenburg-Vorpommern' },
    { value: 'niedersachsen', label: 'Niedersachsen', state: 'Niedersachsen' },
    { value: 'nordrhein-westfalen', label: 'Nordrhein-Westfalen', state: 'Nordrhein-Westfalen' },
    { value: 'rheinland-pfalz', label: 'Rheinland-Pfalz', state: 'Rheinland-Pfalz' },
    { value: 'saarland', label: 'Saarland', state: 'Saarland' },
    { value: 'sachsen', label: 'Sachsen', state: 'Sachsen' },
    { value: 'sachsen-anhalt', label: 'Sachsen-Anhalt', state: 'Sachsen-Anhalt' },
    { value: 'schleswig-holstein', label: 'Schleswig-Holstein', state: 'Schleswig-Holstein' },
    { value: 'thüringen', label: 'Thüringen', state: 'Thüringen' },
]

export const placesIndex = [
  {
    label: 'Bundesländer',
    options: states,
  },
  {
    label: 'Städte',
    options: cities,
  },
];

export const lawAndEconomy = [
  { value: 'betriebswirtschaftslehre', label: 'Betriebswirtschaftslehre'},
  { value: 'management', label: 'Management' },
  { value: 'wirtschaftswissenschaften', label: 'Wirtschaftswissenschaften / VWL' },
  { value: 'wirtschaft', label: 'Wirtschaft und Ingenieurwesen'},
  { value: 'internationale wirtschaft', label: 'Internationale Wirtschaft'  },
  { value: 'rechtswissenschaften', label: 'Rechtswissenschaften' },
  { value: 'tourismus', label: 'Tourismus, Events, Veranstaltungen'},
  { value: 'marketing', label: 'Marketing' },
  { value: 'bank', label: 'Bank-Finanz- und Versicherungswesen'},
  { value: 'verwaltung', label: 'Verwaltung' },
];

export const teaching = [
  { value: 'grundschule', label: 'Grundschule' },
  { value: 'hauptschule', label: 'Hauptschule' },
  { value: 'mittelschule', label: 'Mittelschule' },
  { value: 'gymnasium', label: 'Gymnasium' },
  { value: 'berufsschule', label: 'berufsschule' },
  { value: 'förderschule', label: 'Förderschule' },
];

export const stem = [
    { value: 'informatik', label: 'Informatik' },
    { value: 'elektro- und informationstechnik', label: 'Elektro- und Informationstechnik' },
    { value: 'maschinenbau', label: 'Maschinenbau' },
    { value: 'wirtschaft und ingenieurwesen', label: 'Wirtschaft und Ingenieurwesen' },
    { value: 'mathematik', label: 'Mathematik' },
    { value: 'ingenieurwissenschaften (allgemeine)', label: 'Ingenieurwissenschaften (allgemeine)' },
    { value: 'bauingenieurwesen', label: 'Bauingenieurwesen' },
    { value: 'biotechnologie/ -ingenieurwesen', label: 'Biotechnologie/ -ingenieurwesen' },

    { value: 'stadt- und raumplanung, verkehrswesen', label: 'Stadt- und Raumplanung, Verkehrswesen' },
    { value: 'fahrzeug- und verkehrstechnik', label: 'Fahrzeug- und Verkehrstechnik' },
    { value: 'technischer umweltschutz', label: 'Technischer Umweltschutz' },
    { value: 'bibliotheks- und informationswesen', label: 'Bibliotheks- und Informationswesen' },
    { value: 'architektur', label: 'Architektur' },
    { value: 'medizintechnik', label: 'Medizintechnik' },
    { value: 'versorgungstechnik', label: 'Versorgungstechnik' },
    { value: 'lebensmitteltechnologie/-chemie', label: 'Lebensmitteltechnologie/-chemie' },

    { value: 'feinwerk- und mikrotechnik', label: 'Feinwerk- und Mikrotechnik' },
    { value: 'medien- und drucktechnik', label: 'Medien- und Drucktechnik' },
    { value: 'bergbau, hüttenwesen', label: 'Bergbau, Hüttenwesen' },
    { value: 'textil- und bekleidungstechnik', label: 'Textil- und Bekleidungstechnik' },
    { value: 'seefahrt, nautik', label: 'Seefahrt, Nautik' },
    { value: 'vermessungswesen', label: 'Vermessungswesen' },


]

export const naturalScience = [
    { value: 'biologie', label: 'Biologie' },
    { value: 'physik', label: 'Physik' },
    { value: 'chemie', label: 'Chemie' },
    { value: 'geographie', label: 'Geographie' },
    { value: 'biotechnologie/ -ingenieurwesen', label: 'Biotechnologie/ -ingenieurwesen' },
    { value: 'geowissenschaften', label: 'Geowissenschaften' },
    { value: 'Umweltwissenschaften', label: 'Umweltwissenschaften' },
    { value: 'haushalts- und ernährungswissenschaften', label: 'Haushalts- und Ernährungswissenschaften' },
]

export const socialStudies = [
    { value: 'erziehungswissenschaften', label: 'Erziehungswissenschaften' },
    { value: 'geschichtswissenschaften', label: 'Geschichtswissenschaften' },
    { value: 'sozialwissenschaften', label: 'Sozialwissenschaften' },
    { value: 'theologie', label: 'Theologie' },
    { value: 'religionswissenschaften, philosophie', label: 'Religionswissenschaften, Philosophie' },
    { value: 'psychologie', label: 'Psychologie' },
    { value: 'sozialarbeit, sozialwesen', label: 'Sozialarbeit, Sozialwesen' },

    { value: 'politikwissenschaft', label: 'Politikwissenschaft' },
    { value: 'geographie', label: 'Geographie' },
    { value: 'stadt- und raumplanung, verkehrswesen', label: 'Stadt- und Raumplanung, Verkehrswesen' },
    { value: 'verwaltung', label: 'Verwaltung' },
    { value: 'haushalts- und ernährungswissenschaften', label: 'Haushalts- und Ernährungswissenschaften' },
    { value: 'verbrecherbekämpfung', label: 'Verbrecherbekämpfung' },

]

export const mediaStudies = [
    { value: 'medienwissenschaften', label: 'Medienwissenschaften' },
    { value: 'kommunikationswissenschaften', label: 'Kommunikationswissenschaften' },
    { value: 'Theather, Film, TV, Regie', label: 'Theather, Film, TV, Regie' },
    { value: 'marketing', label: 'Marketing' },
    { value: 'haushalts- und ernährungswissenschaften', label: 'Haushalts- und Ernährungswissenschaften' },
    { value: 'journalistik, publizistik', label: 'Journalistik, Publizistik' },

]

export const medicalStudies = [
    { value: 'pflege- und gesundheitswissenschaften', label: 'Pflege- und Gesundheitswissenschaften' },
    { value: 'psychologie', label: 'Psychologie' },
    { value: 'sport', label: 'Sport' },
    { value: 'medizin', label: 'Medizin' },
    { value: 'medizintechnik', label: 'Medizintechnik' },
    { value: 'therapien', label: 'Therapien' },
    { value: 'pharmazie', label: 'Pharmazie' },

]

export const artStudies = [
    { value: 'musik (instrument, gesant, dirigieren)', label: 'Musik (Instrument, Gesant, Dirigieren)' },
    { value: 'design / gestaltung', label: 'Design / Gestaltung' },
    { value: 'kunst (freue / angewandte)', label: 'Kunst (freue / angewandte)' },
    { value: 'theater, film, tv, regie', label: 'Theater, Film, TV, Regie' },
    { value: 'architektur', label: 'Architektur' },
    { value: 'musikwissenschaften', label: 'Musikwissenschaften' },
    { value: 'kunstgeschichte, kunstwissenschaften', label: 'Kunstgeschichte, Kunstwissenschaften' },
    { value: 'medien- und drucktechnik', label: 'Medien- und Drucktechnik' },
]

export const languageStudies = [
    { value: 'neuere philologie', label: 'neuere Philologie' },
    { value: 'kulturwissenschaften', label: 'Kulturwissenschaften' },
    { value: 'klassische philologie', label: 'klassische Philologie' },
    { value: 'sprach- und sprechwissenschaften', label: 'Sprach- und Sprechwissenschaften' },
    { value: 'tourismus, rvents, veranstaltungen', label: 'Tourismus, Events, Veranstaltungen' },
    { value: 'bibliotheks- und informationswesenn', label: 'Bibliotheks- und Informationswesen' },
    { value: 'musikwissenschaften', label: 'Musikwissenschaften' },
    { value: 'kunstgeschichte, kunstwissenschaften', label: 'Kunstgeschichte, Kunstwissenschaften' },
    { value: 'übersetzen und dolmetschen', label: 'Übersetzen und Dolmetschen' },
]

export const agriculturalStudies = [
    { value: 'agrarwissenschaften', label: 'Agrarwissenschaften' },
    { value: 'landschaftsplanung/-architektur', label: 'Landschaftsplanung/-architektur' },
    { value: 'gartenbau', label: 'Gartenbau' },
    { value: 'forstwissenschaften', label: 'Forstwissenschaften' },
    { value: 'wasser und boden', label: 'Wasser und Boden' },
    { value: 'tierwissenschaften', label: 'Tierwissenschaften' },
]



export const studyDirection = [
  {
    label: 'Rechts- und Wirtschaftswissenschaften, Verwaltung',
    options: lawAndEconomy,
  },
  {
    label: 'Lehrämter',
    options: teaching,
  },
  {
      label: 'Ingenieurwissenschaften, Mathematik, Informatik',
      options: stem,
  },
  {
      label: 'Naturwissenschaften',
      options: naturalScience,
  },
  {
      label: 'Gesellschafts- und Sozialwissenschaften',
      options: socialStudies,
  },
  {
      label: 'Medien und Kommunikation',
      options: mediaStudies,
  },
  {
      label: 'Medizin, Gesundheitswesen, Sport',
      options: medicalStudies,
  },
  {
      label: 'Musik, Kunst und Gestaltung',
      options: artStudies,
  },
  {
      label: 'Sprach- und Kulturwissenschaften',
      options: languageStudies,
  },
  {
      label: 'Agrar- und Forstwissenschaften',
      options: agriculturalStudies,
  }

];

export const art = [
    { value: 'architektur', label: 'Architektur', topic: 'architecture'},
{ value: 'kreativität', label: 'Kreativität', topic: 'creative'},
{ value: 'drama', label: 'Drama', topic: 'drama'},
{ value: 'zeichnen', label: 'Zeichnen', topic: 'draw'},
{ value: 'improv', label: 'Improv', topic: 'improv'},
{ value: 'theater', label: 'Theater', topic: 'live-theatre'},
]

export const career = [
    { value: 'buchhaltung', label: 'Buchhaltung', topic: 'accounting'},
{ value: 'marketing', label: 'Marketing', topic: 'advertising'},
{ value: 'karriere', label: 'Karriere', topic: 'careers'},
{ value: 'unternehmensberatung', label: 'Unternehmensberatung', topic: 'consultant'},
{ value: 'vwl', label: 'VWL', topic: 'economics'},
{ value: 'investment', label: 'Investment', topic: 'investing'},
{ value: 'job suche', label: 'Job Suche', topic: 'job-search'},
]

export const cars = [
    { value: 'autos', label: 'Autos', topic: 'cars'},
]

export const environment = [
    { value: 'alternative energien', label: 'Alternative Energien', topic: 'alternativeenergy'},
{ value: 'wohltätigkeit', label: 'Wohltätigkeit', topic: 'charity'},
{ value: 'umwelt', label: 'Umwelt', topic: 'environment'},
{ value: 'tanzen', label: 'Tanzen', topic: ''},
{ value: 'ballet', label: 'Ballet', topic: 'ballet'},
]

export const education = [
    { value: 'biologie', label: 'Biologie', topic: 'biology'},
{ value: 'debattieren', label: 'Debattieren', topic: 'debates'},
{ value: 'ingenieurwesen', label: 'Ingenieurwesen', topic: 'engineering'},
{ value: 'geschichte', label: 'Geschichte', topic: 'history'},
{ value: 'philosophie', label: 'Philosophie', topic: 'philosophy'},
]
export const terms = [
    {
        label: 'Kunst & Kultur',
        options: art,
    },
    {
        label: 'Karriere & Business',
        options: career,
    },
    {
        label: 'Auto & Motorrad',
        options: cars,
    },
    {
        label: 'Gemeinschaft & Umwelt',
        options: environment,
    },
    {
        label: 'Bildung & Lernen',
        options: education,
    }


]
