DROP TABLE IF EXISTS deals;


CREATE TABLE deals(
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    type VARCHAR(100),
    organizer VARCHAR(300),
    description TEXT NOT NULL,
    place VARCHAR(300),
    event_date VARCHAR(300),
    creation_date VARCHAR(300),
    other TEXT,
    link TEXT NOT NULL,
    ts_event TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO deals (name, description, other, link) VALUES ('Amazon Music Unlimited- 3 Monate gratis für Studenten','Amazon Music Unlimited ist ein Musik-Streaming-Service, der Zugriff auf mehr als 50 Millionen Songs, akuelle Neuerscheinungen und Hörspiele bietet. Hören Sie zusätzlich alle Spiele der Bundesliga, der 2. Bundesliga und des DFB-Pokals live. Online, offline und ohne Werbung.Exklusiv für teilnahmeberechtigte Prime Student-Mitglieder: Teilnahmeberechtigt sind alle Prime Student-Mitglieder, die derzeit an einer Universität oder Hochschule eingeschrieben sind, die zu einem Hochschulabschluss führt.','','https://www.amazon.de/b?ie=UTF8&node=14798208031');
INSERT INTO deals (name, description, other, link) VALUES ('GoPro Hero 7 Black Action Cam - Studenten Rabatt','Unidays hat den Rabatt auf der offiziellen GoPro Homepage von 15% auf 20% erhöht.Dadurch lässt sich noch mehr sparen und der Preis fällt auf 343,99€. ','','https://de.shop.gopro.com/cameras?cjevent=2995b1f103e011e9822600050a180512');
INSERT INTO deals (name, description, other, link) VALUES ('Deezer Premium für Studenten!','Für Studenten im Alter von 18-25 Jahren. Dir wird 12 Monate lang 4,99 € pro Monat berechnet. Nach Ende des Angebots wird dir der Standardpreis von 9,99 € pro Monat berechnet, sofern du das Angebot nicht erneuerst. Nutzer, die bisher noch keinen kostenlosen Testzeitraum von Deezer in Anspruch genommen haben, erhalten zusätzlich 30 Tage kostenlos, wenn sie Zahlungsdaten angeben. Dieses Angebot kann höchstens dreimal erneuert werden','','https://www.deezer.com/de/offers/student/?utm_source=google&utm_medium=search-obj_sub&utm_campaign=acq-sea&utm_term=student&utm_content=student&gclid=CjwKCAiAodTfBRBEEiwAa1hauv4TF4zsuN81-OTGHHZ2gCm0waAl7VeaIIVTfQSYk2AVp7Z_k8eI_RoC8EgQAvD_BwE');
INSERT INTO deals (name, description, other, link) VALUES ('Vodafone Mobilfunk Studententarife','Vodafone Mobilfunk StudententarifeVodafone bietet erstklassige Tarife zu günstigen Preisen und ist damit die richtige Adresse, wenn du auf der Suche nach einem neuen Handyvertrag bist. Um in den Genuss der Vodafone-Specials für junge Leute zu kommen, musst du zwischen 18 und 28 Jahre alt sein. Der Provider bietet sowohl für den normalen Durchschnittssurfer als auch den 24/7-Surfer den passenden Tarif. So gibt es drei verschiedene Varianten von Young, wobei du jeweils zwischen 2, 6 oder sogar 12 GB wählen kannst! ','','https://www.vodafone.de/privat/handys-tablets-tarife/junge-leute.html?simOnly=1&tarifSKU=sku2944261&b_id=1743&c_id=affl_content_cic_103:fq0_C_gen_sta_jls&j_id=AffconPer103C|NonNon000|fq0gensta');
INSERT INTO deals (name, description, other, link) VALUES ('HP: Bis zu 37% Studentenrabatt','HP steht für Qualität und fortschrittliche Technologien und ist damit ein zuverlässiger Begleiter für dich und dein Studium. Im HP Studentenstore kannst du dich mit großartigen Rabatten perfekt für den Alltag in und außerhalb der Uni rüsten. Präsentationen anfertigen und drucken? Kein Problem mit der großen Auswahl an HP Notebooks, Tinte/Toner und HP Druckern. Auf alles, was dein IT-Herz begehrt sowie auf sämtliches Zubehör bekommst du im HP Studentenstore bis zu 30% Studentenrabatt.','','https://store.hp.com/GermanyStore/Merch/Default.aspx?jumpid=af_6x3ywb7zj8&');
INSERT INTO deals (name, description, other, link) VALUES ('EMP: 15% Studentenrabatt','EMP ist ein Online-Shop, der sich auf Merchandise-Produkte spezialisiert hat: Shoppe über 30.000 Fanartikel, Clothing von Badeshorts über T-Shirts bis hin zu Schuhen aus dem Heavy Metal-, Rock- und Entertainment-Segment und genieße jede Menge Special Editions und namenhafte Marken und Brands. Temporäre Sale-Aktion lassen jedes Musik- und Serien-Herz höher schlagen.Jetzt neu: 15% Studentenrabatt im EMP ShopSpare als Student neuerdings 15% auf deinen Lieblings-Merch im EMP Online Shop. Folge unserem Link und registriere dich bei EMP als Student und schon kannst du 15% Studentenrabatt aufs komplette Sortiment einheimsen. Rock on!','','https://www.emp.de/student-discount.html?wt_mc=pt.aff.68180.www.allmaxx.de..1.354.&adc=de');
INSERT INTO deals (name, description, other, link) VALUES ('Krankenversicherung für Studenten','Noch bevor es mit dem Studium losgeht, solltest du dir überlegen, wie du dich als Studierender krankenversichern möchtest – denn grundsätzlich wirst du versicherungspflichtig, sobald du immatrikuliert bist. Für die Entscheidung, ob du dich gesetzlich oder privat krankenversichern willst, hast du maximal drei Monate ab dem Zeitpunkt der Einschreibung Zeit. Normalerweise bist du jedoch noch über deine Eltern familienversichert','','https://studentenkrankenkasse.de/');
INSERT INTO deals (name, description, other, link) VALUES ('Studentenrabatt für Flüge','Wir bieten in Kooperation mit Opodo Studentenrabatte auf Flüge zu deinem nächsten Urlaubsziel.Willst du dem Studienalltag für eine Weile entfliehen? Schaufel dir ein paar Tage frei und nimm dir Zeit zum Abschalten und Relaxen. Reisen können ein Loch im Geldbeutel eines jeden Studierenden hinterlassen. Wie du trotz kleinem Budget verreisen kannst, erfährst du hier.','','https://www.opodo.de/?utm_term=flight&awc=9133_1545259945_34826046ee05da83f98b03e890807b32&mktportal=affiliatewindow&utm_source=affiliatewindow&utm_medium=affiliates&utm_campaign=400097&utm_term=flights&utm_content=Discount+Code');
INSERT INTO deals (name, description, other, link) VALUES ('Microsoft Surface Spar-Bundle: Nur 489€','Profitiere jetzt von einem tollen Angebot bei Saturn: Sichere dir das Microsoft Surface Go mit Type Cover und Microsoft Office 365 im Spar-Bundle für 489 € statt 575,98 €. Klicke dich dazu einfach weiter zu unserer Partnerseite Studentenrabatt.com und hol dir den Gutscheincode, mit dem du rund 100 € sparst.Microsoft Surface Go mit Type Cover und Microsoft Office 365: 100 € StudentenrabattHol dir mit diesem Spar-Bundle von Saturn alles, was du brauchst: Ein leistungsfähiges Notebook mit dem Microsoft Surface Go, das dazugehörige Type Pad, damit du neben dem praktischen Tablet-Erlebnis auch komfortabel schreiben kannst sowie Microsoft Office 365 mit Excel, Word und PowerPoint. 1 Angebot der Extraklasse!','','https://allmaxx.de/studentenrabatt/saturn-microsoft-bundle');
